<!DOCTYPE html>
<html lang="th">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Talk To Figma MCP — Complete Setup Guide</title>
  <style>
    :root {
      --bg: #ffffff;
      --bg-secondary: #f8f9fb;
      --bg-code: #1e1e2e;
      --text: #1a1a2e;
      --text-secondary: #555770;
      --accent: #a259ff;
      --accent-light: #f0e6ff;
      --accent-dark: #7b2edd;
      --green: #1bc47d;
      --green-light: #e6f9f0;
      --blue: #0d99ff;
      --blue-light: #e5f4ff;
      --orange: #ff8c00;
      --orange-light: #fff4e5;
      --red: #f24822;
      --red-light: #fde8e4;
      --border: #e4e4eb;
      --shadow: 0 2px 12px rgba(0,0,0,0.06);
      --shadow-lg: 0 8px 30px rgba(0,0,0,0.08);
      --radius: 12px;
      --radius-sm: 8px;
    }

    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans Thai', sans-serif;
      background: var(--bg-secondary);
      color: var(--text);
      line-height: 1.7;
      font-size: 16px;
    }

    /* ─── Hero ─── */
    .hero {
      background: linear-gradient(135deg, #1a1a2e 0%, #2d1b69 50%, #a259ff 100%);
      color: white;
      padding: 60px 24px 50px;
      text-align: center;
      position: relative;
      overflow: hidden;
    }
    .hero::before {
      content: '';
      position: absolute;
      top: -50%; left: -50%;
      width: 200%; height: 200%;
      background: radial-gradient(circle at 30% 50%, rgba(162,89,255,0.15) 0%, transparent 50%),
                  radial-gradient(circle at 70% 80%, rgba(13,153,255,0.1) 0%, transparent 50%);
      animation: float 20s ease-in-out infinite;
    }
    @keyframes float {
      0%, 100% { transform: translate(0, 0); }
      50% { transform: translate(-20px, -10px); }
    }
    .hero > * { position: relative; z-index: 1; }
    .hero-badge {
      display: inline-block;
      background: rgba(255,255,255,0.15);
      backdrop-filter: blur(10px);
      border: 1px solid rgba(255,255,255,0.2);
      padding: 6px 16px;
      border-radius: 20px;
      font-size: 13px;
      font-weight: 500;
      letter-spacing: 0.5px;
      margin-bottom: 20px;
    }
    .hero h1 {
      font-size: clamp(28px, 5vw, 44px);
      font-weight: 800;
      letter-spacing: -0.5px;
      margin-bottom: 12px;
    }
    .hero h1 span { color: #a259ff; background: linear-gradient(135deg, #a259ff, #0d99ff); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
    .hero p {
      font-size: 17px;
      opacity: 0.85;
      max-width: 640px;
      margin: 0 auto;
      line-height: 1.6;
    }
    .hero-logos {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 16px;
      margin-top: 28px;
      font-size: 14px;
      opacity: 0.7;
    }
    .hero-logos .connector { font-size: 20px; }

    /* ─── Layout ─── */
    .container {
      max-width: 860px;
      margin: 0 auto;
      padding: 0 20px;
    }

    /* ─── TOC ─── */
    .toc {
      background: var(--bg);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 28px 32px;
      margin: -30px auto 40px;
      position: relative;
      z-index: 2;
      box-shadow: var(--shadow-lg);
    }
    .toc h2 {
      font-size: 15px;
      text-transform: uppercase;
      letter-spacing: 1.5px;
      color: var(--text-secondary);
      margin-bottom: 16px;
    }
    .toc-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
      gap: 6px;
    }
    .toc a {
      display: flex;
      align-items: center;
      gap: 10px;
      padding: 8px 12px;
      border-radius: var(--radius-sm);
      text-decoration: none;
      color: var(--text);
      font-size: 14.5px;
      font-weight: 500;
      transition: all 0.15s;
    }
    .toc a:hover { background: var(--accent-light); color: var(--accent-dark); }
    .toc-num {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 24px; height: 24px;
      background: var(--accent-light);
      color: var(--accent);
      border-radius: 6px;
      font-size: 12px;
      font-weight: 700;
      flex-shrink: 0;
    }

    /* ─── Sections ─── */
    .section {
      background: var(--bg);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 36px 36px;
      margin-bottom: 24px;
      box-shadow: var(--shadow);
    }
    .section h2 {
      font-size: 24px;
      font-weight: 700;
      margin-bottom: 6px;
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .section h2 .num {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 36px; height: 36px;
      background: var(--accent);
      color: white;
      border-radius: 10px;
      font-size: 16px;
      font-weight: 800;
      flex-shrink: 0;
    }
    .section-subtitle {
      color: var(--text-secondary);
      font-size: 15px;
      margin-bottom: 24px;
      padding-left: 48px;
    }
    .section h3 {
      font-size: 18px;
      font-weight: 700;
      margin: 28px 0 12px;
      padding-bottom: 8px;
      border-bottom: 2px solid var(--bg-secondary);
    }
    .section h3:first-of-type { margin-top: 0; }
    .section h4 {
      font-size: 15px;
      font-weight: 700;
      margin: 20px 0 8px;
      color: var(--accent-dark);
    }
    .section p { margin-bottom: 12px; }
    .section ul, .section ol {
      margin: 0 0 16px 20px;
    }
    .section li { margin-bottom: 6px; }

    /* ─── Capability list ─── */
    .cap-list {
      list-style: none;
      margin-left: 0 !important;
      padding: 0;
    }
    .cap-list li {
      padding: 6px 0 6px 28px;
      position: relative;
    }
    .cap-list li::before {
      content: '✓';
      position: absolute;
      left: 0;
      color: var(--green);
      font-weight: 700;
    }
    .limit-list {
      list-style: none;
      margin-left: 0 !important;
      padding: 0;
    }
    .limit-list li {
      padding: 6px 0 6px 28px;
      position: relative;
      color: var(--text-secondary);
    }
    .limit-list li::before {
      content: '✗';
      position: absolute;
      left: 0;
      color: var(--red);
      font-weight: 700;
    }

    /* ─── Tables ─── */
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
      font-size: 14.5px;
    }
    thead th {
      background: var(--bg-secondary);
      padding: 10px 14px;
      text-align: left;
      font-weight: 700;
      font-size: 13px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: var(--text-secondary);
      border-bottom: 2px solid var(--border);
    }
    tbody td {
      padding: 10px 14px;
      border-bottom: 1px solid var(--border);
      vertical-align: top;
    }
    tbody tr:hover { background: var(--bg-secondary); }
    tbody tr:last-child td { border-bottom: none; }

    /* ─── Code ─── */
    code {
      background: var(--bg-secondary);
      border: 1px solid var(--border);
      padding: 2px 7px;
      border-radius: 5px;
      font-family: 'SF Mono', 'Fira Code', 'Consolas', monospace;
      font-size: 13.5px;
      color: var(--accent-dark);
    }
    pre {
      background: var(--bg-code);
      color: #cdd6f4;
      padding: 20px 24px;
      border-radius: var(--radius-sm);
      overflow-x: auto;
      margin: 12px 0 16px;
      font-family: 'SF Mono', 'Fira Code', 'Consolas', monospace;
      font-size: 13.5px;
      line-height: 1.65;
      position: relative;
    }
    pre code {
      background: none;
      border: none;
      padding: 0;
      color: inherit;
    }
    .lang-label {
      position: absolute;
      top: 8px; right: 12px;
      font-size: 11px;
      color: #6c7086;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    /* syntax colors */
    .cm { color: #6c7086; }
    .kw { color: #cba6f7; }
    .str { color: #a6e3a1; }
    .fn { color: #89b4fa; }
    .num { color: #fab387; }
    .flag { color: #f9e2af; }

    /* ─── Info boxes ─── */
    .info-box {
      border-radius: var(--radius-sm);
      padding: 16px 20px;
      margin: 16px 0;
      font-size: 14.5px;
      display: flex;
      gap: 12px;
      align-items: flex-start;
    }
    .info-box .icon { font-size: 18px; flex-shrink: 0; margin-top: 1px; }
    .info-box.tip { background: var(--green-light); border-left: 4px solid var(--green); }
    .info-box.warn { background: var(--orange-light); border-left: 4px solid var(--orange); }
    .info-box.note { background: var(--blue-light); border-left: 4px solid var(--blue); }
    .info-box.danger { background: var(--red-light); border-left: 4px solid var(--red); }

    /* ─── Architecture diagram ─── */
    .arch-diagram {
      background: linear-gradient(135deg, #1a1a2e, #2d1b69);
      border-radius: var(--radius);
      padding: 32px 24px;
      margin: 20px 0;
      overflow-x: auto;
    }
    .arch-grid {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 16px;
      flex-wrap: wrap;
    }
    .arch-box {
      background: rgba(255,255,255,0.08);
      backdrop-filter: blur(10px);
      border: 1px solid rgba(255,255,255,0.15);
      border-radius: 12px;
      padding: 20px;
      text-align: center;
      color: white;
      min-width: 160px;
      flex: 1;
      max-width: 200px;
    }
    .arch-box .arch-icon { font-size: 32px; margin-bottom: 8px; }
    .arch-box .arch-title { font-size: 14px; font-weight: 700; margin-bottom: 4px; }
    .arch-box .arch-desc { font-size: 12px; opacity: 0.65; }
    .arch-arrow {
      color: rgba(255,255,255,0.4);
      font-size: 24px;
      flex-shrink: 0;
    }
    .arch-subtitle {
      text-align: center;
      color: rgba(255,255,255,0.5);
      font-size: 13px;
      margin-top: 16px;
    }

    /* ─── Step cards ─── */
    .step-card {
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 24px 28px;
      margin: 20px 0;
      position: relative;
      background: var(--bg);
    }
    .step-card::before {
      content: attr(data-step);
      position: absolute;
      top: -12px; left: 24px;
      background: var(--accent);
      color: white;
      font-size: 12px;
      font-weight: 700;
      padding: 3px 14px;
      border-radius: 12px;
      letter-spacing: 0.5px;
    }
    .step-card.green::before { background: var(--green); }
    .step-card.blue::before { background: var(--blue); }
    .step-card.orange::before { background: var(--orange); }
    .step-card h4 {
      margin-top: 6px;
      font-size: 17px;
      color: var(--text);
    }

    /* ─── Quick ref box ─── */
    .quick-ref {
      background: linear-gradient(135deg, #1a1a2e, #16213e);
      border-radius: var(--radius);
      padding: 28px 28px;
      margin: 20px 0;
      color: white;
    }
    .quick-ref h4 { color: #a6e3a1; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 16px; }
    .quick-ref-steps {
      list-style: none;
      padding: 0;
    }
    .quick-ref-steps li {
      display: flex;
      gap: 14px;
      padding: 12px 0;
      border-bottom: 1px solid rgba(255,255,255,0.08);
      align-items: flex-start;
    }
    .quick-ref-steps li:last-child { border-bottom: none; }
    .qr-num {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 28px; height: 28px;
      background: rgba(162,89,255,0.3);
      color: #cba6f7;
      border-radius: 8px;
      font-size: 13px;
      font-weight: 700;
      flex-shrink: 0;
    }
    .qr-content { flex: 1; }
    .qr-label { font-size: 13px; color: rgba(255,255,255,0.5); margin-bottom: 2px; }
    .qr-cmd {
      font-family: 'SF Mono', 'Fira Code', monospace;
      font-size: 13px;
      color: #a6e3a1;
      background: rgba(255,255,255,0.05);
      padding: 4px 10px;
      border-radius: 6px;
      display: inline-block;
      margin-top: 4px;
    }

    /* ─── Cheat sheet ─── */
    .cheat-group { margin: 20px 0; }
    .cheat-group h4 {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      background: var(--accent-light);
      color: var(--accent-dark);
      padding: 5px 14px;
      border-radius: 20px;
      font-size: 13px;
      font-weight: 700;
      margin-bottom: 12px;
    }

    /* ─── Troubleshoot cards ─── */
    .trouble-card {
      border: 1px solid var(--border);
      border-radius: var(--radius-sm);
      margin: 16px 0;
      overflow: hidden;
    }
    .trouble-header {
      background: var(--red-light);
      padding: 12px 20px;
      font-weight: 700;
      font-size: 15px;
      display: flex;
      gap: 8px;
      align-items: center;
      cursor: pointer;
      user-select: none;
    }
    .trouble-header:hover { filter: brightness(0.97); }
    .trouble-body {
      padding: 16px 20px;
    }
    .trouble-body p { margin-bottom: 8px; }
    .trouble-body strong { color: var(--text); }

    /* ─── Glossary ─── */
    .glossary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
      gap: 10px;
      margin: 16px 0;
    }
    .glossary-item {
      background: var(--bg-secondary);
      border-radius: var(--radius-sm);
      padding: 12px 16px;
    }
    .glossary-item dt {
      font-weight: 700;
      font-size: 14px;
      color: var(--accent-dark);
      margin-bottom: 2px;
    }
    .glossary-item dd {
      font-size: 13.5px;
      color: var(--text-secondary);
    }

    /* ─── Footer ─── */
    .footer {
      text-align: center;
      padding: 40px 20px;
      color: var(--text-secondary);
      font-size: 14px;
    }
    .footer a { color: var(--accent); text-decoration: none; }

    /* ─── Responsive ─── */
    @media (max-width: 640px) {
      .section { padding: 24px 20px; }
      .toc { padding: 20px; }
      .toc-grid { grid-template-columns: 1fr; }
      .arch-grid { flex-direction: column; }
      .arch-arrow { transform: rotate(90deg); }
      .arch-box { max-width: 100%; }
    }

    /* ─── Print ─── */
    @media print {
      body { background: white; }
      .hero { background: #1a1a2e !important; }
      .section { break-inside: avoid; box-shadow: none; border: 1px solid #ddd; }
    }

    /* ─── Collapsible / details ─── */
    details {
      border: 1px solid var(--border);
      border-radius: var(--radius-sm);
      margin: 12px 0;
      overflow: hidden;
    }
    details[open] { border-color: var(--accent); }
    summary {
      padding: 14px 20px;
      font-weight: 700;
      font-size: 15px;
      cursor: pointer;
      display: flex;
      align-items: center;
      gap: 10px;
      background: var(--bg-secondary);
      transition: all 0.15s;
      list-style: none;
      user-select: none;
    }
    summary::-webkit-details-marker { display: none; }
    summary::before {
      content: '▶';
      font-size: 10px;
      color: var(--accent);
      transition: transform 0.2s;
      flex-shrink: 0;
    }
    details[open] > summary::before { transform: rotate(90deg); }
    summary:hover { background: var(--accent-light); }
    details[open] > summary { background: var(--accent-light); border-bottom: 1px solid var(--border); }
    .details-body { padding: 20px 24px; font-size: 14.5px; }
    .details-body h4 {
      font-size: 15px;
      font-weight: 700;
      margin: 20px 0 8px;
      color: var(--accent-dark);
      padding-bottom: 4px;
      border-bottom: 1px solid var(--bg-secondary);
    }
    .details-body h4:first-child { margin-top: 0; }
    .details-body h5 {
      font-size: 14px;
      font-weight: 700;
      margin: 16px 0 6px;
      color: var(--text);
    }
    .details-body p { margin-bottom: 10px; }
    .details-body ul, .details-body ol { margin: 0 0 12px 20px; }
    .details-body li { margin-bottom: 4px; font-size: 14px; }
    .details-body table { font-size: 13.5px; }
    .details-body pre { font-size: 13px; }

    /* ─── Skill file badge ─── */
    .file-badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      background: var(--bg-secondary);
      border: 1px solid var(--border);
      padding: 4px 12px;
      border-radius: 20px;
      font-size: 12px;
      font-family: 'SF Mono', 'Fira Code', monospace;
      color: var(--text-secondary);
      margin: 4px 0 12px;
    }
    .file-badge .dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; }
    .file-badge .dot.skill { background: var(--accent); }
    .file-badge .dot.ref { background: var(--blue); }

    /* ─── Flow diagram ─── */
    .flow-row {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      flex-wrap: wrap;
      margin: 16px 0;
    }
    .flow-step {
      background: linear-gradient(135deg, var(--accent), var(--accent-dark));
      color: white;
      padding: 10px 18px;
      border-radius: 10px;
      font-size: 13px;
      font-weight: 600;
      text-align: center;
      min-width: 100px;
    }
    .flow-arrow { color: var(--text-secondary); font-size: 18px; flex-shrink: 0; }

    /* ─── Install cmd box ─── */
    .install-box {
      background: linear-gradient(135deg, #0f172a, #1e293b);
      border-radius: var(--radius);
      padding: 24px;
      margin: 16px 0;
      color: #e2e8f0;
    }
    .install-box h4 { color: #a6e3a1; font-size: 13px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 12px; }
    .install-box .path {
      font-family: 'SF Mono', 'Fira Code', monospace;
      font-size: 13px;
      color: #fbbf24;
      background: rgba(255,255,255,0.05);
      padding: 3px 8px;
      border-radius: 4px;
    }
    .install-box ol { margin: 12px 0 0 20px; }
    .install-box li { margin-bottom: 8px; font-size: 14px; }
    .install-box code {
      background: rgba(255,255,255,0.08);
      border: none;
      color: #a6e3a1;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 12.5px;
    }

    /* smooth scroll */
    html { scroll-behavior: smooth; }
  </style>
</head>
<body>

<!-- ════════════════════ HERO ════════════════════ -->
<header class="hero">
  <div class="hero-badge">KNOWLEDGE SHARING 2025</div>
  <h1>Talk To Figma <span>MCP</span></h1>
  <h1 style="font-size:clamp(20px,3vw,28px); font-weight:400; opacity:0.9;">Complete Setup Guide</h1>
  <p>เชื่อมต่อ <strong>Claude AI</strong> กับ <strong>Figma Desktop</strong><br>
  ให้ AI ช่วยสร้างและแก้ไข Design ใน Figma ได้โดยตรง<br>
  ตั้งแต่ขั้นตอนแรก จนใช้งานได้จริง</p>
  <div class="hero-logos">
    <span>VS Code</span>
    <span class="connector">+</span>
    <span>Claude AI</span>
    <span class="connector">+</span>
    <span>Figma</span>
  </div>
</header>

<div class="container">

<!-- ════════════════════ TOC ════════════════════ -->
<nav class="toc">
  <h2>สารบัญ</h2>
  <div class="toc-grid">
    <a href="#sec1"><span class="toc-num">1</span> ภาพรวม — มันคืออะไร?</a>
    <a href="#sec2"><span class="toc-num">2</span> สถาปัตยกรรม</a>
    <a href="#sec3"><span class="toc-num">3</span> สิ่งที่ต้องเตรียม</a>
    <a href="#sec4"><span class="toc-num">4</span> ติดตั้ง (ทำครั้งเดียว)</a>
    <a href="#sec5"><span class="toc-num">5</span> ใช้งานรายวัน</a>
    <a href="#sec6"><span class="toc-num">6</span> วิธีใช้งานจริง</a>
    <a href="#sec7"><span class="toc-num">7</span> Cheat Sheet</a>
    <a href="#sec8"><span class="toc-num">8</span> Troubleshooting</a>
    <a href="#sec9"><span class="toc-num">9</span> Tips &amp; Best Practices</a>
    <a href="#sec10"><span class="toc-num" style="background:#e5f4ff;color:#0d99ff;">10</span> Skill & วิธีติดตั้ง</a>
    <a href="#sec11"><span class="toc-num" style="background:#e5f4ff;color:#0d99ff;">11</span> Reference Files ทั้งหมด</a>
    <a href="#glossary"><span class="toc-num">A</span> คำศัพท์สำคัญ</a>
  </div>
</nav>

<!-- ════════════════════ 1. OVERVIEW ════════════════════ -->
<section class="section" id="sec1">
  <h2><span class="num">1</span> ภาพรวม</h2>
  <p class="section-subtitle">มันคืออะไร? ทำอะไรได้?</p>

  <h3>มันคืออะไร?</h3>
  <p><a href="https://www.figma.com/community/plugin/1485687494525374295" target="_blank" style="color:var(--accent); font-weight:600; text-decoration:none; border-bottom:2px solid var(--accent-light);">Talk To Figma MCP Plugin</a> คือระบบที่ทำให้ <strong>Claude AI</strong> สามารถ:</p>
  <ul class="cap-list">
    <li>สร้าง Frame, Rectangle, Text, Shape ใน Figma ได้</li>
    <li>แก้ไขสี, ขนาด, ตำแหน่ง, Auto Layout ของ element ที่มีอยู่แล้วได้</li>
    <li>อ่านข้อมูล document, selection, styles, components ได้</li>
    <li>Clone, Delete, Export element ได้</li>
    <li>ใช้ Components จาก local library ได้</li>
  </ul>

  <h3>ทำไมถึงน่าใช้?</h3>
  <table>
    <thead><tr><th>สิ่งที่ทำได้</th><th>ตัวอย่าง</th></tr></thead>
    <tbody>
      <tr><td>สร้าง UI จากคำอธิบาย</td><td>"สร้างหน้า Login แบบ iOS ให้หน่อย"</td></tr>
      <tr><td>แก้ไข design ที่มี</td><td>"เปลี่ยนปุ่มเป็นสีน้ำเงิน, เพิ่ม corner radius 12"</td></tr>
      <tr><td>สร้าง Layout ซ้ำๆ เร็ว</td><td>"สร้าง card 10 ใบ เรียงกัน"</td></tr>
      <tr><td>ออกแบบตาม Design System</td><td>"สร้างหน้าจอตาม Material Design 3"</td></tr>
    </tbody>
  </table>

  <h3>ข้อจำกัด</h3>
  <ul class="limit-list">
    <li>ไม่สามารถสร้าง Vector/Pen tool ซับซ้อนได้</li>
    <li>ไม่สามารถ import รูปภาพจาก URL ได้โดยตรง</li>
    <li>ไม่สามารถใช้ Prototype/Interaction ได้</li>
    <li>ต้องเปิด Figma Desktop (ใช้ผ่าน browser ไม่ได้)</li>
  </ul>
</section>

<!-- ════════════════════ 2. ARCHITECTURE ════════════════════ -->
<section class="section" id="sec2">
  <h2><span class="num">2</span> สถาปัตยกรรม</h2>
  <p class="section-subtitle">แต่ละชิ้นเชื่อมกันยังไง?</p>

  <h3>แผนผังการเชื่อมต่อ</h3>
  <div class="arch-diagram">
    <div class="arch-grid">
      <div class="arch-box">
        <div class="arch-icon">💻</div>
        <div class="arch-title">VS Code + Claude</div>
        <div class="arch-desc">เราพิมพ์คำสั่ง<br>AI คิดแล้วสั่งงาน</div>
      </div>
      <div class="arch-arrow">→</div>
      <div class="arch-box">
        <div class="arch-icon">🔌</div>
        <div class="arch-title">MCP Server</div>
        <div class="arch-desc">ตัวแปลคำสั่ง<br>Claude → Figma</div>
      </div>
      <div class="arch-arrow">→</div>
      <div class="arch-box">
        <div class="arch-icon">📡</div>
        <div class="arch-title">WebSocket Server</div>
        <div class="arch-desc">ตัวส่งข้อความ<br>real-time</div>
      </div>
      <div class="arch-arrow">→</div>
      <div class="arch-box">
        <div class="arch-icon">🎨</div>
        <div class="arch-title">Figma + Plugin</div>
        <div class="arch-desc">รับคำสั่งแล้ว<br>สร้าง design จริง</div>
      </div>
    </div>
    <div class="arch-subtitle">ทุกอย่างรันอยู่บนเครื่องเรา (localhost)</div>
  </div>

  <h3>อธิบายแต่ละชิ้น</h3>
  <table>
    <thead><tr><th>ชิ้นส่วน</th><th>คืออะไร</th><th>ทำหน้าที่อะไร</th></tr></thead>
    <tbody>
      <tr><td><strong>VS Code + Claude Code</strong></td><td>Editor + AI</td><td>เราพิมพ์คำสั่ง, AI คิดแล้วสั่งงาน</td></tr>
      <tr><td><strong>MCP Server (stdio)</strong></td><td>ตัวแปลภาษา</td><td>แปลคำสั่ง AI เป็นคำสั่ง Figma</td></tr>
      <tr><td><strong>WebSocket Server</strong></td><td>ตัวส่งข้อความ</td><td>ส่งคำสั่งระหว่าง MCP กับ Figma Plugin</td></tr>
      <tr><td><strong>Figma Plugin</strong></td><td>หูของ Figma</td><td>รับคำสั่งแล้วทำงานจริงใน Figma</td></tr>
    </tbody>
  </table>

  <h3>Channel ID คืออะไร?</h3>
  <p>Channel ID เปรียบเสมือน <strong>"ห้องแชท"</strong> ที่ Claude กับ Figma Plugin ใช้คุยกัน:</p>
  <ul>
    <li>ทุกครั้งที่เปิด Figma Plugin ใหม่ จะได้ <strong>Channel ID ใหม่</strong></li>
    <li>ต้องบอก Claude ว่า Channel ID คืออะไร เพื่อให้เข้าห้องเดียวกัน</li>
    <li>ถ้า Channel ID ไม่ตรงกัน = <strong>คุยกันไม่ได้</strong></li>
  </ul>
</section>

<!-- ════════════════════ 3. PREREQUISITES ════════════════════ -->
<section class="section" id="sec3">
  <h2><span class="num">3</span> สิ่งที่ต้องเตรียม</h2>
  <p class="section-subtitle">Prerequisites</p>

  <h3>Software ที่ต้องติดตั้ง</h3>
  <table>
    <thead><tr><th>#</th><th>Software</th><th>ทำไมต้องใช้</th><th>ดาวน์โหลด</th></tr></thead>
    <tbody>
      <tr><td>1</td><td><strong>VS Code</strong></td><td>Editor สำหรับใช้งาน Claude</td><td><a href="https://code.visualstudio.com" target="_blank">code.visualstudio.com</a></td></tr>
      <tr><td>2</td><td><strong>Node.js</strong> (v18+)</td><td>Runtime สำหรับรัน server</td><td><a href="https://nodejs.org" target="_blank">nodejs.org</a> (เลือก LTS)</td></tr>
      <tr><td>3</td><td><strong>Figma Desktop</strong></td><td>ต้องใช้ Desktop app เท่านั้น</td><td><a href="https://www.figma.com/downloads" target="_blank">figma.com/downloads</a></td></tr>
    </tbody>
  </table>

  <h3>Account ที่ต้องมี</h3>
  <table>
    <thead><tr><th>#</th><th>Account</th><th>หมายเหตุ</th></tr></thead>
    <tbody>
      <tr><td>1</td><td><strong>Anthropic Account</strong></td><td>สำหรับใช้ Claude (ต้อง subscribe plan)</td></tr>
      <tr><td>2</td><td><strong>Figma Account</strong></td><td>Free plan ก็ใช้ได้</td></tr>
    </tbody>
  </table>
</section>

<!-- ════════════════════ 4. INSTALLATION ════════════════════ -->
<section class="section" id="sec4">
  <h2><span class="num">4</span> ขั้นตอนติดตั้ง</h2>
  <p class="section-subtitle">ทำครั้งเดียว ไม่ต้องทำซ้ำ (ยกเว้นมีบอกไว้)</p>

  <!-- 4.1 -->
  <div class="step-card" data-step="STEP 4.1">
    <h4>ติดตั้ง VS Code</h4>
    <ol>
      <li>ดาวน์โหลด VS Code จาก <a href="https://code.visualstudio.com" target="_blank">code.visualstudio.com</a></li>
      <li>ติดตั้งตามปกติ (macOS: ลาก .app เข้า Applications)</li>
      <li>เปิด VS Code ทดสอบว่าใช้ได้</li>
    </ol>
  </div>

  <!-- 4.2 -->
  <div class="step-card green" data-step="STEP 4.2">
    <h4>ติดตั้ง Node.js</h4>
    <ol>
      <li>ดาวน์โหลด Node.js จาก <a href="https://nodejs.org" target="_blank">nodejs.org</a> (เลือกปุ่ม <strong>LTS</strong>)</li>
      <li>ติดตั้งตามปกติ</li>
      <li>เปิด <strong>Terminal</strong> (กด <code>Cmd + Space</code> พิมพ์ "Terminal")</li>
      <li>พิมพ์คำสั่งเพื่อเช็คว่าติดตั้งสำเร็จ:</li>
    </ol>
    <pre><code><span class="fn">node</span> <span class="flag">--version</span></code></pre>
    <p>ต้องได้ผลลัพธ์แบบนี้ (เลข version อาจต่างกัน):</p>
    <pre><code>v22.x.x</code></pre>

    <p>5. ติดตั้ง <strong>bun</strong> (package manager ที่เร็วกว่า npm):</p>
    <pre><code><span class="fn">npm</span> install <span class="flag">-g</span> bun</code></pre>

    <div class="info-box warn">
      <span class="icon">⚠️</span>
      <div>ถ้าเจอ error <code>permission denied</code> ให้เติม <code>sudo</code> ข้างหน้า:<br>
      <code>sudo npm install -g bun</code> แล้วใส่ password เครื่อง</div>
    </div>
  </div>

  <!-- 4.3 -->
  <div class="step-card blue" data-step="STEP 4.3">
    <h4>ติดตั้ง Claude Code Extension ใน VS Code</h4>
    <ol>
      <li>เปิด VS Code</li>
      <li>กดที่ไอคอน <strong>Extensions</strong> (แถบซ้าย รูปสี่เหลี่ยม 4 ชิ้น) หรือกด <code>Cmd + Shift + X</code></li>
      <li>ค้นหา <strong>"Claude Code"</strong></li>
      <li>กด <strong>Install</strong> ที่ extension ของ <strong>Anthropic</strong></li>
      <li>หลัง install เสร็จ จะมี icon Claude ขึ้นที่แถบซ้าย</li>
      <li>กดเปิด Claude panel แล้ว <strong>Login</strong> ด้วย Anthropic Account</li>
    </ol>

    <div class="info-box note">
      <span class="icon">💡</span>
      <div><strong>ทางเลือก: ติดตั้ง Claude Code CLI แทน</strong><br>
      ถ้าชอบใช้ Terminal มากกว่า:<br>
      <code>npm install -g @anthropic-ai/claude-code</code><br>
      แล้วพิมพ์ <code>claude</code> ใน Terminal เพื่อเริ่มใช้งาน</div>
    </div>
  </div>

  <!-- 4.4 -->
  <div class="step-card orange" data-step="STEP 4.4">
    <h4>ติดตั้ง Figma Plugin "Talk to Figma"</h4>
    <p style="margin-bottom:12px;">
      <a href="https://www.figma.com/community/plugin/1485687494525374295" target="_blank" style="display:inline-flex; align-items:center; gap:8px; padding:10px 18px; background:linear-gradient(135deg,#ff8c00,#e67700); color:white; text-decoration:none; border-radius:10px; font-weight:700; font-size:14px;">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>
        เปิดหน้า Plugin บน Figma Community
      </a>
    </p>
    <ol>
      <li>กดลิงก์ด้านบน หรือเปิด <strong>Figma Desktop</strong> แล้วค้นหา plugin เอง</li>
      <li>ในหน้า Figma Community กด <strong>"Open in..."</strong> → เลือก Figma Desktop</li>
      <li>กด <strong>Install</strong> (หรือ Save)</li>
      <li>ตอนนี้ plugin พร้อมใช้แล้ว (ยังไม่ต้องเปิด)</li>
    </ol>
    <div class="info-box tip">
      <span class="icon">⚡</span>
      <div><strong>วิธีค้นหาเร็วใน Figma:</strong> กด <code>Cmd + /</code> (Quick Actions) แล้วพิมพ์ "Cursor Talk To Figma"</div>
    </div>
  </div>

  <!-- 4.5 -->
  <div class="step-card" data-step="STEP 4.5">
    <h4>ตั้งค่า MCP Server (ครั้งแรก)</h4>
    <div class="info-box note">
      <span class="icon">ℹ️</span>
      <div><strong>MCP = Model Context Protocol</strong> — มาตรฐานการเชื่อมต่อ AI กับ tools ภายนอก</div>
    </div>
    <p>เปิด <strong>Terminal</strong> ใน VS Code (กด <code>Ctrl + `</code>) แล้วรันคำสั่งนี้:</p>
    <pre><code><span class="fn">claude</span> mcp add TalkToFigma <span class="flag">--</span> bunx cursor-talk-to-figma-mcp@latest <span class="flag">--channel=</span><span class="str">CHANNEL_ID_ตรงนี้</span></code></pre>
    <div class="info-box warn">
      <span class="icon">⏸️</span>
      <div><strong>ยังไม่ต้องรันตอนนี้!</strong> — เราจะได้ Channel ID จริงในขั้นตอนที่ 5 (ขั้นตอนรายวัน)</div>
    </div>
  </div>

  <!-- 4.6 -->
  <div class="step-card green" data-step="STEP 4.6 — OPTIONAL">
    <h4>ตั้งค่า Figma Remote MCP (แนะนำ)</h4>
    <div class="info-box note">
      <span class="icon">🔍</span>
      <div><strong>Figma Remote MCP</strong> ทำให้ Claude อ่าน Design จาก Figma URL ได้ (ดึง specs, screenshot)<br>
      ต่างจาก Talk to Figma ที่เป็นการ "สร้าง/แก้ไข" design</div>
    </div>
    <ol>
      <li>เปิด Terminal แล้วรัน:</li>
    </ol>
    <pre><code><span class="fn">claude</span> mcp add figma <span class="flag">--transport</span> sse <span class="flag">--url</span> <span class="str">https://modelcontextprotocol.servers.figma.com/sse</span></code></pre>
    <ol start="2">
      <li>Claude จะเปิด browser ให้ Login กับ Figma</li>
      <li>กด <strong>Allow</strong> เพื่ออนุญาตการเข้าถึง</li>
      <li>Login ครั้งเดียว ไม่ต้องทำซ้ำ</li>
    </ol>
  </div>
</section>

<!-- ════════════════════ 5. DAILY ROUTINE ════════════════════ -->
<section class="section" id="sec5">
  <h2><span class="num">5</span> ขั้นตอนใช้งานรายวัน</h2>
  <p class="section-subtitle">ทำทุกครั้งที่เปิดเครื่องใหม่ หรือทุกครั้งที่ต้องการเชื่อมต่อ</p>

  <!-- 5.1 -->
  <div class="step-card green" data-step="STEP 5.1">
    <h4>เปิด WebSocket Server</h4>
    <ol>
      <li>เปิด <strong>Terminal</strong> (หน้าต่างใหม่ แยกจาก VS Code ก็ได้)</li>
      <li>รันคำสั่ง:</li>
    </ol>
    <pre><code><span class="fn">bunx</span> cursor-talk-to-figma-socket</code></pre>
    <p>3. จะเห็นข้อความแบบนี้:</p>
    <pre><code>WebSocket server is running on ws://localhost:3055</code></pre>
    <div class="info-box danger">
      <span class="icon">🚨</span>
      <div><strong>ปล่อยหน้าต่างนี้เปิดค้างไว้ ห้ามปิด!</strong><br>
      นี่คือตัวส่งข้อความระหว่าง Claude กับ Figma — เหมือนเปิดวิทยุสื่อสารทิ้งไว้ ถ้าปิดก็คุยกันไม่ได้</div>
    </div>
  </div>

  <!-- 5.2 -->
  <div class="step-card blue" data-step="STEP 5.2">
    <h4>เปิด Figma Plugin แล้วจด Channel ID</h4>
    <ol>
      <li>เปิด <strong>Figma Desktop</strong></li>
      <li>เปิดไฟล์ที่จะทำงาน</li>
      <li>คลิกขวาที่ canvas → <strong>Plugins</strong> → <strong>Cursor Talk To Figma</strong></li>
      <li>Plugin จะเปิดขึ้นมา แสดง <strong>Channel ID</strong>:</li>
    </ol>
    <pre style="background:#f8f9fb; color:#1a1a2e; border:2px dashed #a259ff; text-align:center; font-size:15px;">
  ┌──────────────────────────────┐
  │  Cursor Talk To Figma        │
  │                              │
  │  Channel: <strong style="color:#a259ff">abc123xyz</strong>          │  ← นี่คือ Channel ID
  │                              │
  │  Status: Connected ✓         │
  └──────────────────────────────┘</pre>
    <p>5. <strong>Copy Channel ID</strong> นี้ไว้ (เช่น <code>abc123xyz</code>)</p>
    <div class="info-box warn">
      <span class="icon">⚠️</span>
      <div><strong>สำคัญ:</strong> Channel ID จะเปลี่ยนทุกครั้งที่เปิด plugin ใหม่!</div>
    </div>
  </div>

  <!-- 5.3 -->
  <div class="step-card orange" data-step="STEP 5.3">
    <h4>อัปเดต Channel ID ให้ Claude</h4>
    <p>เปิด <strong>Terminal อีกหน้าต่างหนึ่ง</strong> (ไม่ใช่หน้าต่างที่รัน WebSocket) แล้วรัน 2 คำสั่งนี้:</p>
    <pre><code><span class="cm"># 1. ลบ config เก่า</span>
<span class="fn">claude</span> mcp remove TalkToFigma

<span class="cm"># 2. เพิ่ม config ใหม่ด้วย Channel ID ใหม่</span>
<span class="fn">claude</span> mcp add TalkToFigma <span class="flag">--</span> bunx cursor-talk-to-figma-mcp@latest <span class="flag">--channel=</span><span class="str">abc123xyz</span></code></pre>
    <div class="info-box warn">
      <span class="icon">✏️</span>
      <div>เปลี่ยน <code>abc123xyz</code> เป็น <strong>Channel ID จริง</strong>ที่ copy มา!</div>
    </div>
  </div>

  <!-- 5.4 -->
  <div class="step-card" data-step="STEP 5.4">
    <h4>เปิด Claude แล้วเริ่มใช้งาน</h4>
    <ol>
      <li>เปิด <strong>VS Code</strong></li>
      <li>เปิด <strong>Claude Code panel</strong> (icon Claude ที่แถบซ้าย)</li>
      <li>ทดสอบว่าเชื่อมต่อได้ โดยพิมพ์:</li>
    </ol>
    <pre style="background:#e6f9f0; color:#1a1a2e; border-left:4px solid #1bc47d;"><code>ช่วยดูข้อมูล document ใน Figma ให้หน่อย</code></pre>
    <p>4. ถ้าเชื่อมต่อสำเร็จ Claude จะแสดงข้อมูล document กลับมา 🎉</p>
  </div>

  <!-- Quick Reference -->
  <div class="quick-ref">
    <h4>📋 สรุปขั้นตอนรายวัน (Quick Reference)</h4>
    <ul class="quick-ref-steps">
      <li>
        <span class="qr-num">1</span>
        <div class="qr-content">
          <div class="qr-label">Terminal #1 — ปล่อยเปิดค้าง</div>
          <span class="qr-cmd">bunx cursor-talk-to-figma-socket</span>
        </div>
      </li>
      <li>
        <span class="qr-num">2</span>
        <div class="qr-content">
          <div class="qr-label">Figma Desktop</div>
          <span class="qr-cmd">เปิด Plugin → จด Channel ID</span>
        </div>
      </li>
      <li>
        <span class="qr-num">3</span>
        <div class="qr-content">
          <div class="qr-label">Terminal #2 — อัปเดต Channel ID</div>
          <span class="qr-cmd">claude mcp remove TalkToFigma</span><br>
          <span class="qr-cmd">claude mcp add TalkToFigma -- bunx cursor-talk-to-figma-mcp@latest --channel=&lt;ID&gt;</span>
        </div>
      </li>
      <li>
        <span class="qr-num">4</span>
        <div class="qr-content">
          <div class="qr-label">VS Code</div>
          <span class="qr-cmd">เปิด Claude → ใช้งานได้เลย!</span>
        </div>
      </li>
    </ul>
  </div>
</section>

<!-- ════════════════════ 6. USAGE ════════════════════ -->
<section class="section" id="sec6">
  <h2><span class="num">6</span> วิธีใช้งานจริง</h2>
  <p class="section-subtitle">สั่ง AI ทำงานใน Figma</p>

  <h3>6.1 — พื้นฐาน: สั่ง Claude สร้าง Design</h3>
  <p>เมื่อเชื่อมต่อเสร็จแล้ว สามารถสั่งงาน Claude ด้วย<strong>ภาษาธรรมชาติ</strong>:</p>
  <table>
    <thead><tr><th>พิมพ์</th><th>Claude จะทำ</th></tr></thead>
    <tbody>
      <tr><td>"สร้าง frame ขนาด iPhone 15 Pro"</td><td>สร้าง frame 393×852 px</td></tr>
      <tr><td>"สร้างปุ่ม Login สีน้ำเงิน"</td><td>สร้าง frame + text + สี + radius</td></tr>
      <tr><td>"ดูว่าตอนนี้เลือกอะไรอยู่"</td><td>อ่าน selection แล้วบอก</td></tr>
      <tr><td>"เปลี่ยนสีพื้นหลังเป็น #F5F5F5"</td><td>set fill color ให้ element ที่เลือก</td></tr>
      <tr><td>"จัด auto layout แนวตั้ง spacing 16"</td><td>ตั้ง auto layout ให้ frame ที่เลือก</td></tr>
    </tbody>
  </table>

  <h3>6.2 — สร้างหน้าจอจาก Spec</h3>
  <p>สามารถบอก Claude ให้ออกแบบหน้าจอทั้งหน้าได้:</p>
  <pre style="background:#f0e6ff; color:#1a1a2e; border-left:4px solid #a259ff;"><code>สร้างหน้า Login สำหรับ iOS ใน Figma ให้หน่อย ประกอบด้วย:
- Logo ด้านบน
- Text field สำหรับ Email
- Text field สำหรับ Password
- ปุ่ม Log In สีน้ำเงิน
- ลิงก์ "Forgot Password?"
- ปุ่ม Sign Up ด้านล่าง</code></pre>
  <p>Claude จะ:</p>
  <ol>
    <li>สร้าง main frame ขนาด iPhone</li>
    <li>สร้างแต่ละ component ทีละชิ้น</li>
    <li>จัด layout ด้วย auto layout</li>
    <li>ตั้งสี, font, spacing ให้เหมาะสม</li>
  </ol>

  <h3>6.3 — แก้ไข Design ที่มีอยู่</h3>
  <pre style="background:#e5f4ff; color:#1a1a2e; border-left:4px solid #0d99ff;"><code>ดู element ที่เลือกอยู่ แล้วเปลี่ยนสีเป็น #007AFF</code></pre>
  <pre style="background:#e5f4ff; color:#1a1a2e; border-left:4px solid #0d99ff;"><code>เพิ่ม corner radius 16 ให้ frame ที่เลือก</code></pre>
  <pre style="background:#e5f4ff; color:#1a1a2e; border-left:4px solid #0d99ff;"><code>เปลี่ยน text ของปุ่มจาก "Submit" เป็น "ส่งข้อมูล"</code></pre>

  <h3>6.4 — ใช้งานร่วมกับ Figma Remote MCP</h3>
  <p>ถ้าตั้งค่า Figma Remote MCP ไว้แล้ว (Step 4.6) สามารถส่ง Figma URL ให้ Claude อ่าน design ได้:</p>
  <pre style="background:#e6f9f0; color:#1a1a2e; border-left:4px solid #1bc47d;"><code>ดู design จากลิงก์นี้แล้วสร้างให้เหมือนกัน:
https://figma.com/design/xxxxx/MyDesign?node-id=1-2</code></pre>
</section>

<!-- ════════════════════ 7. CHEAT SHEET ════════════════════ -->
<section class="section" id="sec7">
  <h2><span class="num">7</span> คำสั่งที่ใช้บ่อย</h2>
  <p class="section-subtitle">Cheat Sheet</p>

  <div class="cheat-group">
    <h4>🔍 ดูข้อมูล</h4>
    <table>
      <thead><tr><th>สิ่งที่อยากทำ</th><th>พิมพ์</th></tr></thead>
      <tbody>
        <tr><td>ดูข้อมูล document</td><td>"ดูข้อมูล document ใน Figma"</td></tr>
        <tr><td>ดู element ที่เลือก</td><td>"ดู element ที่เลือกอยู่"</td></tr>
        <tr><td>ดู styles ทั้งหมด</td><td>"แสดง styles ใน document"</td></tr>
        <tr><td>ดู components ทั้งหมด</td><td>"แสดง local components"</td></tr>
        <tr><td>ดู text ทั้งหมดใน frame</td><td>"scan text ทั้งหมดใน frame ที่เลือก"</td></tr>
      </tbody>
    </table>
  </div>

  <div class="cheat-group">
    <h4>➕ สร้าง Element</h4>
    <table>
      <thead><tr><th>สิ่งที่อยากทำ</th><th>พิมพ์</th></tr></thead>
      <tbody>
        <tr><td>สร้าง frame</td><td>"สร้าง frame ชื่อ Header ขนาด 393×80"</td></tr>
        <tr><td>สร้าง text</td><td>"สร้าง text 'Hello World' font size 24 bold"</td></tr>
        <tr><td>สร้าง rectangle</td><td>"สร้างสี่เหลี่ยมขนาด 100×100 สีแดง"</td></tr>
        <tr><td>Clone element</td><td>"clone element ที่เลือก"</td></tr>
        <tr><td>สร้าง component instance</td><td>"สร้าง instance ของ component 'Button'"</td></tr>
      </tbody>
    </table>
  </div>

  <div class="cheat-group">
    <h4>✏️ แก้ไข Element</h4>
    <table>
      <thead><tr><th>สิ่งที่อยากทำ</th><th>พิมพ์</th></tr></thead>
      <tbody>
        <tr><td>เปลี่ยนสี</td><td>"เปลี่ยนสีเป็น #FF0000"</td></tr>
        <tr><td>เปลี่ยนขนาด</td><td>"ปรับขนาดเป็น 200×50"</td></tr>
        <tr><td>เปลี่ยนตำแหน่ง</td><td>"ย้ายไปตำแหน่ง x=100 y=200"</td></tr>
        <tr><td>เปลี่ยน text</td><td>"เปลี่ยน text เป็น 'สวัสดี'"</td></tr>
        <tr><td>เพิ่ม corner radius</td><td>"ตั้ง corner radius เป็น 12"</td></tr>
        <tr><td>ตั้ง auto layout</td><td>"ตั้ง auto layout แนวตั้ง spacing 8 padding 16"</td></tr>
        <tr><td>ลบ element</td><td>"ลบ element ที่เลือก"</td></tr>
      </tbody>
    </table>
  </div>
</section>

<!-- ════════════════════ 8. TROUBLESHOOTING ════════════════════ -->
<section class="section" id="sec8">
  <h2><span class="num">8</span> Troubleshooting</h2>
  <p class="section-subtitle">แก้ปัญหาที่พบบ่อย</p>

  <div class="trouble-card">
    <div class="trouble-header">🔴 ปัญหาที่ 1: Claude ไม่ตอบ / ไม่เห็น Figma</div>
    <div class="trouble-body">
      <p><strong>อาการ:</strong> สั่งให้ทำอะไรใน Figma แล้ว Claude ไม่ทำ หรือบอกว่าเชื่อมต่อไม่ได้</p>
      <p><strong>วิธีแก้:</strong></p>
      <ol>
        <li>เช็คว่า <strong>WebSocket Server</strong> ยังรันอยู่ไหม (Terminal ต้องแสดง <code>running on ws://localhost:3055</code>)</li>
        <li>เช็คว่า <strong>Figma Plugin</strong> เปิดอยู่ไหม (ต้องแสดง "Connected")</li>
        <li>เช็คว่า <strong>Channel ID</strong> ตรงกันไหม — ถ้าไม่แน่ใจ ทำ Step 5.2-5.3 ใหม่</li>
        <li>ลอง <strong>ปิดแล้วเปิด Claude Code ใหม่</strong> ใน VS Code</li>
      </ol>
    </div>
  </div>

  <div class="trouble-card">
    <div class="trouble-header">🔴 ปัญหาที่ 2: <code>bunx: command not found</code></div>
    <div class="trouble-body">
      <p><strong>อาการ:</strong> พิมพ์ <code>bunx</code> แล้ว Terminal บอกว่าหาคำสั่งไม่เจอ</p>
      <p><strong>วิธีแก้:</strong></p>
      <pre><code><span class="fn">npm</span> install <span class="flag">-g</span> bun</code></pre>
      <p>ถ้ายังไม่ได้ ลองใช้ <code>npx</code> แทน <code>bunx</code>:</p>
      <pre><code><span class="fn">npx</span> cursor-talk-to-figma-socket</code></pre>
    </div>
  </div>

  <div class="trouble-card">
    <div class="trouble-header">🔴 ปัญหาที่ 3: Port 3055 ถูกใช้อยู่แล้ว</div>
    <div class="trouble-body">
      <p><strong>อาการ:</strong> รัน WebSocket Server แล้วได้ error <code>EADDRINUSE</code></p>
      <p><strong>วิธีแก้:</strong></p>
      <pre><code><span class="cm"># หา process ที่ใช้ port 3055</span>
<span class="fn">lsof</span> <span class="flag">-i</span> :3055

<span class="cm"># Kill process นั้น (แทนที่ PID ด้วยเลขที่เจอ)</span>
<span class="fn">kill</span> <span class="flag">-9</span> PID</code></pre>
      <p>แล้วรัน <code>bunx cursor-talk-to-figma-socket</code> ใหม่</p>
    </div>
  </div>

  <div class="trouble-card">
    <div class="trouble-header">🔴 ปัญหาที่ 4: Figma Plugin แสดง "Disconnected"</div>
    <div class="trouble-body">
      <p><strong>อาการ:</strong> Plugin เปิดอยู่ แต่สถานะเป็น Disconnected</p>
      <p><strong>วิธีแก้:</strong></p>
      <ol>
        <li>ปิด Plugin (กดปุ่ม X)</li>
        <li>เช็คว่า WebSocket Server ยังรันอยู่</li>
        <li>เปิด Plugin ใหม่ (คลิกขวา → Plugins → Cursor Talk To Figma)</li>
        <li>จด Channel ID ใหม่ แล้วอัปเดตให้ Claude (Step 5.3)</li>
      </ol>
    </div>
  </div>

  <div class="trouble-card">
    <div class="trouble-header">🔴 ปัญหาที่ 5: <code>claude: command not found</code></div>
    <div class="trouble-body">
      <p><strong>อาการ:</strong> พิมพ์ <code>claude</code> แล้ว Terminal ไม่รู้จักคำสั่ง</p>
      <p><strong>วิธีแก้:</strong></p>
      <pre><code><span class="fn">npm</span> install <span class="flag">-g</span> @anthropic-ai/claude-code</code></pre>
      <p>หลังติดตั้ง ปิดแล้วเปิด Terminal ใหม่ แล้วพิมพ์ <code>claude --version</code> เพื่อเช็ค</p>
    </div>
  </div>
</section>

<!-- ════════════════════ 9. TIPS ════════════════════ -->
<section class="section" id="sec9">
  <h2><span class="num">9</span> Tips &amp; Best Practices</h2>
  <p class="section-subtitle">เคล็ดลับสำหรับ Designer</p>

  <h3>สำหรับ Designer</h3>
  <ol>
    <li><strong>เลือก element ก่อนสั่ง</strong> — ถ้าอยากแก้ไข element ที่มีอยู่ ให้เลือก (click) element นั้นใน Figma ก่อน แล้วค่อยสั่ง Claude</li>
    <li><strong>บอก Claude ให้ละเอียด</strong> — ยิ่งบอกละเอียด ยิ่งได้ผลลัพธ์ตรงใจ</li>
    <li><strong>ใช้ชื่อสีเป็น hex</strong> — บอก <code>#007AFF</code> ดีกว่าบอก "สีน้ำเงิน"</li>
    <li><strong>บอกขนาดเป็นตัวเลข</strong> — บอก "width 393 height 852" ดีกว่า "ขนาด iPhone"</li>
    <li><strong>ทำทีละ step</strong> — สร้าง frame ก่อน → ใส่ element → จัด layout → ตั้งสี</li>
  </ol>

  <h3>Workflow แนะนำ</h3>
  <div style="display:flex; flex-wrap:wrap; gap:8px; margin:16px 0;">
    <span style="background:var(--accent-light); color:var(--accent-dark); padding:8px 16px; border-radius:20px; font-size:14px; font-weight:600;">1. ร่าง concept</span>
    <span style="color:var(--text-secondary); padding:8px 4px;">→</span>
    <span style="background:var(--blue-light); color:#0066cc; padding:8px 16px; border-radius:20px; font-size:14px; font-weight:600;">2. Claude สร้าง structure</span>
    <span style="color:var(--text-secondary); padding:8px 4px;">→</span>
    <span style="background:var(--green-light); color:#0a7a4a; padding:8px 16px; border-radius:20px; font-size:14px; font-weight:600;">3. Claude ใส่ content</span>
    <span style="color:var(--text-secondary); padding:8px 4px;">→</span>
    <span style="background:var(--orange-light); color:#b35c00; padding:8px 16px; border-radius:20px; font-size:14px; font-weight:600;">4. Review & feedback</span>
    <span style="color:var(--text-secondary); padding:8px 4px;">→</span>
    <span style="background:var(--red-light); color:#c43020; padding:8px 16px; border-radius:20px; font-size:14px; font-weight:600;">5. Fine-tune ด้วยมือ</span>
  </div>

  <h3>สิ่งที่ควรทำเองใน Figma (MCP ทำไม่ได้ / ทำได้ไม่ดี)</h3>
  <ul class="limit-list">
    <li>วาง Image / Illustration</li>
    <li>สร้าง Complex Vector / Icon (มีเฉพาะ rectangle — ไม่มี ellipse, polygon, star)</li>
    <li>ตั้ง Prototype &amp; Interaction</li>
    <li>Fine-tune pixel-perfect alignment</li>
    <li>สร้าง Complex Gradient / Shadow / Blur (ไม่มี set_effects)</li>
    <li>สร้าง/ลบ/เปลี่ยนชื่อ Page</li>
    <li>Group/Ungroup nodes</li>
    <li>แก้ font family/style หลังสร้าง text (ต้องตั้ง fontSize/fontWeight/fontColor ตอน create_text)</li>
    <li>ตั้ง line height, letter spacing, text decoration</li>
    <li>Rename node</li>
  </ul>
</section>

<!-- ════════════════════ 10. SKILL & INSTALL ════════════════════ -->
<section class="section" id="sec10">
  <h2><span class="num" style="background:#0d99ff;">10</span> Skill &amp; วิธีติดตั้งให้ทีม</h2>
  <p class="section-subtitle">Claude Custom Skill สำหรับออกแบบ UI ใน Figma</p>

  <h3>Skill คืออะไร?</h3>
  <p><strong>Skill</strong> (หรือ Custom Slash Command) คือไฟล์ <code>.md</code> ที่สอน Claude ให้ทำงานเฉพาะทาง ไม่ต้องอธิบายทุกครั้ง แค่พิมพ์ <code>/figma-ui-design-spec</code> แล้ว Claude จะรู้เลยว่าต้องทำอะไร</p>

  <h3>Skill ที่มี: <code>figma-ui-design-spec</code></h3>
  <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-ui-design-spec.md</div>
  <p>Skill นี้สั่งให้ Claude สร้าง <strong>UI Design Specification</strong> ที่ครบถ้วน อ้างอิงหลักการออกแบบมาตรฐาน พร้อม preview และสร้างหน้าจอจริงใน Figma ได้</p>

  <!-- Flow -->
  <h4>Flow การทำงานของ Skill</h4>
  <div class="flow-row">
    <div class="flow-step">1. Requirements<br><small>รวบรวมความต้องการ</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#0d99ff,#0066cc);">2. Design Principles<br><small>อ่าน references</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#1bc47d,#0a7a4a);">3. Preview<br><small>สร้าง React preview</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#ff8c00,#cc6600);">4. Iterate<br><small>แก้จนพอใจ</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#f24822,#c43020);">5. Build in Figma<br><small>สร้างจริงผ่าน MCP</small></div>
  </div>

  <!-- Skill detail -->
  <details>
    <summary>📋 รายละเอียด Skill ทั้งหมด</summary>
    <div class="details-body">
      <h4>Step 1: รวบรวม Requirements</h4>
      <p>Claude จะถามข้อมูลเหล่านี้ (ถ้ายังไม่ได้ระบุ):</p>
      <ul>
        <li><strong>Platform</strong>: Mobile (iOS/Android), Web, Desktop, หรือ Cross-platform?</li>
        <li><strong>Screen/Component</strong>: จะออกแบบหน้าจอหรือ component อะไร?</li>
        <li><strong>User Goal</strong>: ผู้ใช้ต้องการทำอะไรบนหน้าจอนี้?</li>
        <li><strong>Detail Level</strong>: ต้องการ Wireframe (Lo-fi) หรือ Hi-fi UI spec?</li>
        <li><strong>Design System</strong>: ใช้ Material Design, HIG, หรือ custom design system?</li>
        <li><strong>Constraints</strong>: มี brand guidelines, สี, font ที่กำหนดไว้ไหม?</li>
        <li><strong>Reference Design</strong>: มี Figma URL ที่อยากให้ดูเป็น reference ไหม? (ใช้ get_screenshot/get_design_context อ่านได้)</li>
      </ul>

      <h4>Step 2: อ่าน Design Principles</h4>
      <p>Claude จะอ่าน reference files ตาม platform ที่เลือก:</p>
      <table>
        <thead><tr><th>ไฟล์</th><th>เมื่อไหร่</th></tr></thead>
        <tbody>
          <tr><td><code>ux-principles.md</code></td><td>อ่านเสมอทุกครั้ง (Nielsen's + Laws of UX + Gestalt)</td></tr>
          <tr><td><code>material-design.md</code></td><td>Android / Web (Material Design 3)</td></tr>
          <tr><td><code>hig.md</code></td><td>iOS / macOS (Apple HIG)</td></tr>
          <tr><td><code>design-tokens.md</code></td><td>Custom Design System</td></tr>
          <tr><td><code>figma-mcp-commands.md</code></td><td>Step 5 — สร้างใน Figma</td></tr>
          <tr><td><code>fontawesome-icons.md</code></td><td>Icon mapping — placeholder → FontAwesome <span style="background:#1bc47d;color:#fff;padding:1px 6px;border-radius:3px;font-size:10px;font-weight:700;">NEW</span></td></tr>
        </tbody>
      </table>

      <h4>Step 3: สร้าง Interactive Preview (React .jsx)</h4>
      <p>Claude สร้างไฟล์ <code>.jsx</code> ที่ render หน้าจอจริงได้ทันที เพื่อให้ดูหน้าตาก่อนสร้างใน Figma</p>
      <p><strong>Preview ต้องมี:</strong></p>
      <ol>
        <li>iPhone/Android frame จำลอง (เช่น 393×852 สำหรับ iPhone 15 Pro)</li>
        <li>Status bar จำลอง (เวลา, battery, signal)</li>
        <li>ทุก component ตาม spec — สี, ขนาด, spacing ถูกต้อง</li>
        <li>Light/Dark mode toggle สลับ theme ได้</li>
        <li>State switcher — ปุ่มเปลี่ยน state (empty, filled, error, loading, success)</li>
        <li>Interactive elements — กรอก input, กดปุ่ม ดู state จริง</li>
        <li>Spec info panel — แสดงค่าสำคัญ (frame size, font, spacing, colors)</li>
      </ol>

      <h4>Step 4: Iterate จนพอใจ</h4>
      <ul>
        <li>ดู preview แล้วขอแก้ไข</li>
        <li>แก้ไข .jsx แล้วให้ดูใหม่</li>
        <li>วนจนกว่าพอใจ</li>
        <li>เมื่อพอใจแล้ว Claude จะถาม: "พร้อมจะสร้างใน Figma ไหมครับ?"</li>
      </ul>

      <h4>Step 5: สร้างใน Figma ผ่าน MCP</h4>
      <p><strong>ลำดับการสร้าง (สำคัญมาก):</strong></p>
      <ol>
        <li>สร้าง Main Frame ด้วย <code>create_frame</code> (พร้อม auto layout + สี + parentId ในคำสั่งเดียว)</li>
        <li>สร้าง child elements จากบนลงล่าง (ใช้ <code>parentId</code> ใส่เข้า parent ได้เลย)</li>
        <li>แต่ละ element: สร้าง → <code>set_corner_radius</code> (ถ้าต้องการ)</li>
        <li>ตั้ง auto layout แยก ถ้าต้องปรับทีหลัง (<code>set_layout_mode</code> + <code>set_padding</code> + <code>set_axis_align</code> + <code>set_layout_sizing</code> + <code>set_item_spacing</code>)</li>
      </ol>
      <div class="info-box warn" style="margin:12px 0;">
        <span class="icon">⚠️</span>
        <div><strong>สำคัญ:</strong> ไม่มีคำสั่ง <code>insert_child</code> — ใช้ <code>parentId</code> ตอนสร้างแทน / ไม่มี <code>set_auto_layout</code> รวม — ต้องแยก 5 คำสั่ง / แก้ font หลังสร้าง text ไม่ได้ — ตั้ง fontSize/fontWeight/fontColor ตอน <code>create_text</code> เท่านั้น</div>
      </div>

      <h4>Step 5.5: Annotate (Optional)</h4>
      <p>ถ้าต้องการ spec annotations บน Figma ใช้ <code>set_multiple_annotations</code> เพิ่มหมายเหตุให้แต่ละ element ได้</p>

      <h4>Output Files</h4>
      <table>
        <thead><tr><th>Step</th><th>Output</th><th>Format</th></tr></thead>
        <tbody>
          <tr><td>3</td><td>Interactive Preview</td><td><code>.jsx</code> (React)</td></tr>
          <tr><td>3</td><td>Design Spec Document</td><td><code>.md</code> (optional)</td></tr>
          <tr><td>5</td><td>Figma Design</td><td>สร้างตรงใน Figma ผ่าน MCP</td></tr>
          <tr><td>5.5</td><td>Figma Annotations</td><td>Annotations บน Figma nodes</td></tr>
        </tbody>
      </table>

      <h4>Design Spec Templates</h4>
      <h5>Wireframe (Lo-fi) Template</h5>
      <pre><code>## 1. Overview
## 2. Layout Structure (with ASCII wireframe)
## 3. Component List (table)
## 4. Navigation Flow
## 5. UX Principles Applied (table with principle + rationale)
## 6. Notes for Figma Implementation</code></pre>

      <h5>Hi-fi Template (เพิ่มจาก Lo-fi)</h5>
      <pre><code>## 7. Visual Design (Colors, Typography, Spacing, Elevation)
## 8. Design Tokens (ถ้าใช้ custom design system)
## 9. Component Specifications (ทุก state)
## 10. Accessibility (contrast, touch targets, labels)
## 11. Responsive Behavior
## 12. Motion &amp; Haptic (iOS)</code></pre>

      <h4>หลักการสำคัญ 10 ข้อ</h4>
      <ol>
        <li><strong>เจาะจงและวัดผลได้</strong>: ระบุตัวเลขเสมอ (px, dp, pt, hex color)</li>
        <li><strong>อ้างอิง Design Principle</strong>: ทุกการตัดสินใจต้องมีเหตุผลหลักการ</li>
        <li><strong>Edge Cases</strong>: empty, loading, error, long text, no data</li>
        <li><strong>Accessibility First</strong>: contrast ratio, touch target, screen reader</li>
        <li><strong>WCAG Contrast Verified</strong>: ทุกคู่สี text/bg ต้องผ่าน WCAG AA ขั้นต่ำ พร้อมระบุค่า ratio</li>
        <li><strong>Platform-Aware</strong>: เคารพ platform conventions</li>
        <li><strong>Preview First</strong>: ให้ดู preview ก่อนสร้างจริงเสมอ</li>
        <li><strong>Figma-Ready</strong>: element names, auto layout, proper layer structure</li>
        <li><strong>Use parentId</strong>: ใส่ elements เข้า parent ตอนสร้างได้เลย ไม่ต้อง insert_child แยก</li>
        <li><strong>Font ตั้งตอนสร้าง</strong>: fontSize, fontWeight, fontColor ตั้งได้ตอน create_text เท่านั้น</li>
      </ol>

      <h4>WCAG Color Contrast Checker (บังคับ)</h4>
      <p>ทุกครั้งที่เลือกสี <strong>ต้องตรวจสอบ WCAG Color Contrast</strong> ก่อนใช้งาน:</p>
      <table>
        <thead><tr><th>ประเภท</th><th>AA (ขั้นต่ำ)</th><th>AAA (แนะนำ)</th></tr></thead>
        <tbody>
          <tr><td>Normal text (&lt; 18pt)</td><td>4.5:1</td><td>7:1</td></tr>
          <tr><td>Large text (&ge; 18pt bold / &ge; 24pt regular)</td><td>3:1</td><td>4.5:1</td></tr>
          <tr><td>UI components &amp; icons</td><td>3:1</td><td>—</td></tr>
        </tbody>
      </table>
      <p style="margin-top:12px;"><strong>ขั้นตอน:</strong></p>
      <ol>
        <li>ก่อนเลือกสี: คำนวณ contrast ratio ระหว่าง text color กับ background color</li>
        <li>ระบุค่า contrast ratio ใน spec เสมอ เช่น: <code>#F0E8FF on #0D0A14 → 15.2:1 ✅ AAA</code></li>
        <li>ถ้าไม่ผ่าน AA: ปรับสีให้ผ่านก่อนใช้ — ห้ามใช้สีที่ไม่ผ่านเกณฑ์</li>
        <li>สรุปตาราง contrast ไว้ใน preview spec info panel</li>
      </ol>
      <pre><code>✅ ผ่าน:
  #F0E8FF on #0D0A14 → 15.2:1 (AAA) — primary text on dark bg
  #4ADE80 on #0D2818 → 6.8:1 (AA)  — positive text on green bg

❌ ไม่ผ่าน:
  #7E6E98 on #1E1830 → 2.8:1 (FAIL) — ต้องปรับให้สว่างขึ้น</code></pre>
    </div>
  </details>

  <!-- ═══ Skill 2: Design Critique ═══ -->
  <h3>Skill 2: <code>figma-design-critique</code> <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></h3>
  <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-design-critique.md</div>
  <p>วิเคราะห์และ review design ที่มีอยู่แล้ว — ให้คะแนน 8 มิติ, ระบุจุดแข็ง/จุดอ่อน, เสนอ improvement พร้อม action items</p>

  <div class="flow-row">
    <div class="flow-step">1. Capture<br><small>รับ design</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#0d99ff,#0066cc);">2. Principles<br><small>อ่าน references</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#1bc47d,#0a7a4a);">3. Analyze<br><small>วิเคราะห์ 8 มิติ</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#ff8c00,#cc6600);">4. Score<br><small>ให้คะแนน</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#f24822,#c43020);">5. Report<br><small>สรุปผล</small></div>
  </div>

  <details>
    <summary>📋 รายละเอียด Design Critique Skill</summary>
    <div class="details-body">
      <h4>8 มิติที่วิเคราะห์</h4>
      <table>
        <thead><tr><th>มิติ</th><th>Weight</th><th>ตรวจอะไร</th></tr></thead>
        <tbody>
          <tr><td>Visual Hierarchy &amp; Layout</td><td>15%</td><td>Information hierarchy, alignment, white space, Gestalt</td></tr>
          <tr><td>Typography</td><td>10%</td><td>Type scale, weight contrast, readability, font families</td></tr>
          <tr><td>Color &amp; Contrast</td><td>15%</td><td>WCAG contrast, palette consistency, semantic colors</td></tr>
          <tr><td>Component Design</td><td>15%</td><td>Platform conventions, button hierarchy, input states</td></tr>
          <tr><td>Spacing &amp; Consistency</td><td>10%</td><td>Spacing system, padding/margin consistency</td></tr>
          <tr><td>UX Heuristics</td><td>20%</td><td>Nielsen's 10 Heuristics ทุกข้อ</td></tr>
          <tr><td>Accessibility</td><td>10%</td><td>Touch targets, color independence, screen reader</td></tr>
          <tr><td>Edge Cases</td><td>5%</td><td>Empty, loading, error, long text, no data</td></tr>
        </tbody>
      </table>

      <h4>Rating Scale</h4>
      <ul>
        <li><strong>9-10</strong>: World-class — ไม่ต้องแก้อะไร</li>
        <li><strong>7-8</strong>: ดี — มี minor improvements</li>
        <li><strong>5-6</strong>: ปานกลาง — ต้องแก้หลายจุด</li>
        <li><strong>3-4</strong>: ต้องปรับปรุง — มีปัญหาพื้นฐาน</li>
        <li><strong>1-2</strong>: ต้อง redesign — ปัญหาร้ายแรง</li>
      </ul>

      <h4>Output: Design Review Report</h4>
      <ul>
        <li>Score breakdown ทุกมิติ + Weighted Total</li>
        <li>Strengths (จุดแข็ง) + Issues (Critical / Major / Minor)</li>
        <li>Contrast Audit table ทุกคู่สี</li>
        <li>Action Items เรียงตาม priority</li>
        <li>Optional: แก้ไขตรงใน Figma ผ่าน MCP ได้เลย</li>
      </ul>
    </div>
  </details>

  <!-- ═══ Skill 3: User Flow ═══ -->
  <h3>Skill 3: <code>figma-user-flow</code> <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></h3>
  <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-user-flow.md</div>
  <p>ออกแบบ User Flow, Information Architecture, Task Flow, Screen Map สำหรับ app/web ทั้งระบบ — สร้าง flow diagram ใน FigJam ได้</p>

  <div class="flow-row">
    <div class="flow-step">1. Requirements<br><small>เข้าใจ product</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#0d99ff,#0066cc);">2. Principles<br><small>Navigation patterns</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#1bc47d,#0a7a4a);">3. Map IA<br><small>Screen hierarchy</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#ff8c00,#cc6600);">4. Design Flows<br><small>Happy + error paths</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#f24822,#c43020);">5. Diagrams<br><small>FigJam / Figma</small></div>
  </div>

  <details>
    <summary>📋 รายละเอียด User Flow Skill</summary>
    <div class="details-body">
      <h4>สิ่งที่ Skill สร้างให้</h4>
      <table>
        <thead><tr><th>Output</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><strong>Feature Inventory</strong></td><td>จัดกลุ่ม features เป็น Must Have / Should Have / Could Have</td></tr>
          <tr><td><strong>Content Model</strong></td><td>Entities, attributes, relationships</td></tr>
          <tr><td><strong>Screen Map</strong></td><td>Hierarchy ของ screens (Level 0-3)</td></tr>
          <tr><td><strong>Navigation Matrix</strong></td><td>ตาราง From/To ว่าแต่ละหน้าไปไหนได้ด้วย transition แบบไหน</td></tr>
          <tr><td><strong>User Flows</strong></td><td>Happy path + error/alternative paths + decision points + edge cases</td></tr>
          <tr><td><strong>Flow Diagrams</strong></td><td>Mermaid.js diagrams ใน FigJam (ผ่าน generate_diagram)</td></tr>
          <tr><td><strong>Screen Map (Figma)</strong></td><td>Visual screen cards + connections ใน Figma</td></tr>
        </tbody>
      </table>

      <h4>Flow Principles ที่ตรวจ</h4>
      <ul>
        <li><strong>Hick's Law</strong>: แต่ละ step ตัวเลือกไม่เกิน 5-7</li>
        <li><strong>Miller's Law</strong>: ข้อมูลต่อหน้าจอไม่เกิน 7±2 chunks</li>
        <li><strong>H1 Visibility</strong>: ผู้ใช้รู้ว่าอยู่ step ไหน</li>
        <li><strong>H3 User Control</strong>: ทุก step มีทางกลับ</li>
        <li><strong>H5 Error Prevention</strong>: ป้องกัน error ก่อน submit</li>
      </ul>
    </div>
  </details>

  <!-- ═══ Skill 4: Accessibility Audit ═══ -->
  <h3>Skill 4: <code>figma-accessibility-audit</code> <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></h3>
  <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-accessibility-audit.md</div>
  <p>ตรวจสอบ Accessibility อย่างครบถ้วนตาม WCAG 2.1 — ครอบคลุม 7 หมวด ไม่ใช่แค่สี</p>

  <div class="flow-row">
    <div class="flow-step">1. Capture<br><small>รับ design</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#0d99ff,#0066cc);">2. Guidelines<br><small>WCAG 2.1</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#1bc47d,#0a7a4a);">3. Audit<br><small>ตรวจ 7 หมวด</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#ff8c00,#cc6600);">4. Score<br><small>WCAG level</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#f24822,#c43020);">5. Report + Fix<br><small>Action items</small></div>
  </div>

  <details>
    <summary>📋 รายละเอียด Accessibility Audit Skill</summary>
    <div class="details-body">
      <h4>7 หมวดที่ตรวจ</h4>
      <table>
        <thead><tr><th>หมวด</th><th>Weight</th><th>ตรวจอะไร</th></tr></thead>
        <tbody>
          <tr><td>Color Contrast</td><td>25%</td><td>WCAG 1.4.3/1.4.6 — ทุกคู่สี text/bg/icon</td></tr>
          <tr><td>Touch Targets</td><td>15%</td><td>WCAG 2.5.5/2.5.8 — 44pt iOS / 48dp Android</td></tr>
          <tr><td>Screen Reader</td><td>20%</td><td>WCAG 1.1.1/4.1.2 — labels, alt text, heading structure, reading order</td></tr>
          <tr><td>Color Independence</td><td>10%</td><td>WCAG 1.4.1 — สีไม่เป็นตัวบ่งชี้เพียงอย่างเดียว</td></tr>
          <tr><td>Keyboard Navigation</td><td>10%</td><td>WCAG 2.1.1/2.4.7 — focus order, focus visible, skip links</td></tr>
          <tr><td>Text &amp; Readability</td><td>10%</td><td>WCAG 1.4.4/1.4.12 — line height, line length, text resize</td></tr>
          <tr><td>Motion &amp; Cognitive</td><td>10%</td><td>WCAG 2.3.1/2.3.3 — reduce motion, auto-play, cognitive load</td></tr>
        </tbody>
      </table>

      <h4>WCAG Compliance Levels</h4>
      <ul>
        <li><strong>A</strong>: ขั้นต่ำสุด — must fix</li>
        <li><strong>AA</strong>: มาตรฐานทั่วไป — target level</li>
        <li><strong>AAA</strong>: สูงสุด — สำหรับ government/healthcare</li>
      </ul>

      <h4>Color Blindness Simulation</h4>
      <p>ตรวจว่า design ใช้งานได้กับ: Protanopia (red-blind), Deuteranopia (green-blind), Tritanopia (blue-blind)</p>

      <h4>Output: Accessibility Audit Report</h4>
      <ul>
        <li>Score + WCAG compliance level</li>
        <li>Detailed findings ทั้ง 7 หมวด</li>
        <li>WCAG Violations Summary (criterion, level, issue, fix)</li>
        <li>Priority Action Items (P0-P3)</li>
        <li>Optional: แก้ไขใน Figma ผ่าน MCP ได้เลย</li>
      </ul>
    </div>
  </details>

  <!-- ═══ Skill 5: Design System ═══ -->
  <h3>Skill 5: <code>figma-design-system</code> <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></h3>
  <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-design-system.md</div>
  <p>สร้าง Design System ทั้งระบบ — ตั้งแต่ color system, typography scale, tokens จนถึง component library พร้อม documentation</p>

  <div class="flow-row">
    <div class="flow-step">1. Requirements<br><small>Brand & scope</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#0d99ff,#0066cc);">2. References<br><small>Token system</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#1bc47d,#0a7a4a);">3. Foundations<br><small>Colors, Type, Spacing</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#ff8c00,#cc6600);">4. Components<br><small>Atoms → Organisms</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#f24822,#c43020);">5. Build + Doc<br><small>Figma + .md</small></div>
  </div>

  <details>
    <summary>📋 รายละเอียด Design System Skill</summary>
    <div class="details-body">
      <h4>Foundations ที่กำหนด</h4>
      <table>
        <thead><tr><th>Foundation</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><strong>Color System</strong></td><td>Color scale (50-950) + Semantic colors + Light/Dark mode + WCAG verified</td></tr>
          <tr><td><strong>Typography Scale</strong></td><td>15 levels (display → label) + font family + weights</td></tr>
          <tr><td><strong>Spacing System</strong></td><td>4px base unit (space-0 ถึง space-20)</td></tr>
          <tr><td><strong>Shape</strong></td><td>Corner radius tokens (none → full)</td></tr>
          <tr><td><strong>Elevation</strong></td><td>Shadow tokens (0-4 levels)</td></tr>
        </tbody>
      </table>

      <h4>Component Hierarchy (Atomic Design)</h4>
      <ul>
        <li><strong>Atoms</strong>: Button, Text Field, Checkbox, Radio, Toggle, Badge, Chip, Avatar</li>
        <li><strong>Molecules</strong>: Search Bar, List Item, Form Field, Menu Item, Tab</li>
        <li><strong>Organisms</strong>: App Bar, Navigation, Card, Dialog, Bottom Sheet, Data Table</li>
      </ul>

      <h4>Per-Component Spec</h4>
      <p>ทุก component กำหนด: Anatomy, Variants, Sizes (S/M/L), States (6 states), Accessibility, Spacing Rules</p>

      <h4>Output</h4>
      <ul>
        <li>Design Tokens (Markdown tables)</li>
        <li>Component Specs (variants × states)</li>
        <li>React Preview (.jsx) — gallery ทั้ง system</li>
        <li>Figma: Foundations + Components frames</li>
        <li>Documentation (.md)</li>
      </ul>
    </div>
  </details>

  <!-- ═══ Skill 6: Responsive Design ═══ -->
  <h3>Skill 6: <code>figma-responsive-design</code> <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></h3>
  <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-responsive-design.md</div>
  <p>ออกแบบ Responsive/Adaptive Design สำหรับหลาย screen size — Mobile, Tablet, Desktop พร้อมสร้างหลาย frames ใน Figma</p>

  <div class="flow-row">
    <div class="flow-step">1. Requirements<br><small>Target sizes</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#0d99ff,#0066cc);">2. References<br><small>Grid & breakpoints</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#1bc47d,#0a7a4a);">3. Breakpoints<br><small>Define sizes</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#ff8c00,#cc6600);">4. Adaptation<br><small>Layout rules</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#f24822,#c43020);">5. Build<br><small>Multi-frame Figma</small></div>
  </div>

  <details>
    <summary>📋 รายละเอียด Responsive Design Skill</summary>
    <div class="details-body">
      <h4>Standard Breakpoints</h4>
      <table>
        <thead><tr><th>Breakpoint</th><th>Width</th><th>Device</th><th>Columns</th></tr></thead>
        <tbody>
          <tr><td>xs</td><td>&lt; 360px</td><td>Small phone</td><td>4</td></tr>
          <tr><td>sm</td><td>360-599px</td><td>Phone</td><td>4</td></tr>
          <tr><td>md</td><td>600-904px</td><td>Tablet portrait</td><td>8</td></tr>
          <tr><td>lg</td><td>905-1239px</td><td>Tablet landscape / Desktop</td><td>12</td></tr>
          <tr><td>xl</td><td>1240-1439px</td><td>Desktop</td><td>12</td></tr>
          <tr><td>2xl</td><td>&ge; 1440px</td><td>Large desktop</td><td>12</td></tr>
        </tbody>
      </table>

      <h4>Layout Adaptation Strategies</h4>
      <table>
        <thead><tr><th>Strategy</th><th>Example</th></tr></thead>
        <tbody>
          <tr><td><strong>Reflow</strong></td><td>Cards stack vertical → horizontal</td></tr>
          <tr><td><strong>Reveal</strong></td><td>Show sidebar ที่ซ่อนบน mobile</td></tr>
          <tr><td><strong>Hide</strong></td><td>ซ่อน non-essential info บน mobile</td></tr>
          <tr><td><strong>Resize</strong></td><td>Image full-width → fixed width</td></tr>
          <tr><td><strong>Transform</strong></td><td>Bottom sheet → side panel</td></tr>
        </tbody>
      </table>

      <h4>Navigation Adaptation</h4>
      <ul>
        <li><strong>Mobile</strong>: Bottom Tab Bar (3-5 items)</li>
        <li><strong>Tablet</strong>: Navigation Rail (side icons)</li>
        <li><strong>Desktop</strong>: Sidebar Navigation (full)</li>
      </ul>

      <h4>Output</h4>
      <ul>
        <li>Breakpoint definitions + adaptation rules</li>
        <li>Responsive Preview (.jsx) — resize ได้ + side-by-side view</li>
        <li>Figma: Multiple frames (Mobile + Tablet + Desktop)</li>
        <li>Annotations อธิบาย adaptation rules</li>
        <li>Connection lines แสดง element mapping ระหว่าง sizes</li>
      </ul>
    </div>
  </details>

  <!-- ═══ Skill 7: UX Writer ═══ -->
  <h3>Skill 7: <code>figma-ux-writer</code> <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></h3>
  <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-ux-writer.md</div>
  <p>เขียน UX Copy ระดับมืออาชีพทั้งไทยและอังกฤษ — microcopy, error messages, CTA, empty states, onboarding ทุกจุดสัมผัสกับผู้ใช้ พร้อมตรวจคำผิด/ไวยากรณ์ทั้งไทย-อังกฤษ และสร้าง Correction Log อ่านแล้วเข้าใจทันที ไม่มีข้อสงสัย</p>

  <div class="flow-row">
    <div class="flow-step">1. Context<br><small>เข้าใจหน้าจอ + ผู้ใช้</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#0d99ff,#0066cc);">2. Voice &amp; Tone<br><small>กำหนด tone</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#1bc47d,#0a7a4a);">3. Write<br><small>TH + EN copy</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#ff8c00,#cc6600);">4. Review<br><small>Spell Check + Correction Log</small></div>
    <span class="flow-arrow">→</span>
    <div class="flow-step" style="background:linear-gradient(135deg,#f24822,#c43020);">5. Apply<br><small>ใส่ text ใน Figma</small></div>
  </div>

  <details>
    <summary>📋 รายละเอียด UX Writer Skill</summary>
    <div class="details-body">
      <h4>Voice Attributes (Standard)</h4>
      <table>
        <thead><tr><th>Attribute</th><th>คำอธิบาย</th></tr></thead>
        <tbody>
          <tr><td><strong>ชัดเจน</strong></td><td>ตรงประเด็น ไม่อ้อมค้อม อ่านรู้เรื่องในครั้งเดียว</td></tr>
          <tr><td><strong>เป็นมิตร</strong></td><td>เข้าถึงง่าย ไม่เป็นทางการเกินไป</td></tr>
          <tr><td><strong>ช่วยเหลือ</strong></td><td>บอกสิ่งที่ต้องทำ ไม่ใช่แค่บอกปัญหา</td></tr>
          <tr><td><strong>เคารพ</strong></td><td>ไม่โทษผู้ใช้ ไม่ใช้ศัพท์เทคนิคโดยไม่จำเป็น</td></tr>
          <tr><td><strong>มั่นใจ</strong></td><td>สื่อสารอย่างแน่นอน ไม่คลุมเครือ</td></tr>
        </tbody>
      </table>

      <h4>Copy Types ที่ครอบคลุม</h4>
      <ul>
        <li><strong>Headlines &amp; Titles</strong> — สั้น, บอก value, active voice</li>
        <li><strong>Buttons &amp; CTAs</strong> — เริ่มด้วยกริยา, เจาะจง, 2-4 คำ</li>
        <li><strong>Form Labels &amp; Placeholders</strong> — ตัวอย่างจริง, optional marking</li>
        <li><strong>Error Messages</strong> — สูตร: [สิ่งที่เกิดขึ้น] + [วิธีแก้]</li>
        <li><strong>Empty States</strong> — สูตร: [สิ่งที่จะอยู่ตรงนี้] + [ทำอย่างไรให้มี]</li>
        <li><strong>Success &amp; Confirmation</strong> — อบอุ่น, ให้ข้อมูล next step</li>
        <li><strong>Destructive Confirmations</strong> — ชัดเจน, บอกผลที่เกิด</li>
        <li><strong>Notifications</strong> — กระชับ, actionable</li>
        <li><strong>Tooltips &amp; Help Text</strong> — สั้นมาก, ตรงประเด็น</li>
        <li><strong>Loading &amp; Progress</strong> — บอกว่ากำลังทำอะไร</li>
        <li><strong>Onboarding</strong> — ตื่นเต้น, บอก value</li>
      </ul>

      <h4>ภาษาไทย — หลักการเฉพาะ</h4>
      <ul>
        <li>ไม่ใช้ "กรุณา" ทุกครั้ง / ไม่ใช้ "ของคุณ" ทุกที่</li>
        <li>สะกดทับศัพท์ตามราชบัณฑิต: "อีเมล" (ไม่ใช่ อีเมล์)</li>
        <li>ทับศัพท์ได้ถ้าคนเข้าใจง่ายกว่าคำไทย</li>
      </ul>

      <h4>ภาษาอังกฤษ — หลักการเฉพาะ</h4>
      <ul>
        <li>Sentence case ไม่ใช่ Title Case</li>
        <li>Use contractions (You're, can't, won't)</li>
        <li>Active voice, front-load keywords</li>
      </ul>

      <h4>Spell &amp; Grammar Check (TH + EN)</h4>
      <ul>
        <li><strong>ตรวจคำผิดภาษาไทย</strong> — ทับศัพท์ผิด (อัพเดท→อัปเดต, อีเมล์→อีเมล, เว็ปไซต์→เว็บไซต์), คำสะกดผิดทั่วไป</li>
        <li><strong>ตรวจคำผิดภาษาอังกฤษ</strong> — Spelling (Recieve→Receive, Succesful→Successful), Grammar (Login vs Log in, Its vs It's)</li>
        <li><strong>ตรวจไวยากรณ์</strong> — ภาษาไทย: ตัด "ทำการ" ซ้ำซ้อน, "สามารถ...ได้" ที่ไม่จำเป็น / ภาษาอังกฤษ: subject-verb agreement</li>
        <li><strong>Correction Log</strong> — บันทึกทุกจุดที่แก้: ตำแหน่ง, ข้อความเดิม, ข้อความที่แก้, ประเภทข้อผิด, เหตุผล พร้อม Summary สรุปจำนวน</li>
      </ul>

      <h4>Output</h4>
      <ul>
        <li><strong>Copy Deck Table</strong> — ทุก element + ไทย/EN + tone + max length</li>
        <li><strong>Terminology Table</strong> — consistency ทั้ง app</li>
        <li><strong>Content Audit</strong> — review copy ที่มีอยู่ พร้อม fix</li>
        <li><strong>Correction Log</strong> — รายการคำผิดที่แก้ + เหตุผล + Summary</li>
        <li>Optional: ใส่ text เข้า Figma ผ่าน <code>set_multiple_text_contents</code></li>
      </ul>
    </div>
  </details>

  <!-- วิธีใช้ Skill -->
  <h3>วิธีใช้ Skill</h3>
  <p>เมื่อติดตั้งเสร็จแล้ว พิมพ์ชื่อ skill ใน Claude หรือพิมพ์ภาษาธรรมชาติ:</p>
  <table>
    <thead><tr><th>Skill Command</th><th>หรือพิมพ์</th><th>ทำอะไร</th></tr></thead>
    <tbody>
      <tr><td><code>/figma-ui-design-spec</code></td><td>"ออกแบบหน้า Login"</td><td>สร้าง UI screen/component</td></tr>
      <tr><td><code>/figma-design-critique</code></td><td>"review design นี้ให้หน่อย"</td><td>วิเคราะห์ + ให้คะแนน design</td></tr>
      <tr><td><code>/figma-user-flow</code></td><td>"ออกแบบ flow ของ app"</td><td>สร้าง user flow + screen map</td></tr>
      <tr><td><code>/figma-accessibility-audit</code></td><td>"ตรวจ accessibility"</td><td>WCAG audit 7 หมวด</td></tr>
      <tr><td><code>/figma-design-system</code></td><td>"สร้าง design system"</td><td>Tokens + components ทั้งระบบ</td></tr>
      <tr><td><code>/figma-responsive-design</code></td><td>"ออกแบบ responsive"</td><td>Multi-breakpoint design</td></tr>
      <tr><td><code>/figma-ux-writer</code></td><td>"เขียน copy หน้า Login"</td><td>UX Copy ไทย + EN</td></tr>
    </tbody>
  </table>
  <p style="margin-top:8px;">Claude จะ trigger skill อัตโนมัติเมื่อเห็นคำที่เกี่ยวข้อง</p>

  <!-- วิธีติดตั้ง -->
  <h3>วิธีติดตั้ง Skill &amp; References ให้ทีม</h3>
  <div class="install-box">
    <h4>📁 โครงสร้างไฟล์ที่ต้องสร้าง</h4>
    <pre style="background:rgba(255,255,255,0.05); border-radius:8px; padding:16px; margin:12px 0;"><code style="color:#e2e8f0; background:none; border:none;">~/.claude/
└── commands/
    ├── figma-ui-design-spec.md          ← Skill 1: สร้าง UI
    ├── figma-design-critique.md         ← Skill 2: Review design
    ├── figma-user-flow.md               ← Skill 3: User Flow / IA
    ├── figma-accessibility-audit.md     ← Skill 4: A11y Audit
    ├── figma-design-system.md           ← Skill 5: Design System
    ├── figma-responsive-design.md       ← Skill 6: Responsive
    ├── figma-ux-writer.md               ← Skill 7: UX Writer (TH+EN)
    └── references/
        ├── ux-principles.md             ← UX Principles
        ├── material-design.md           ← Material Design 3
        ├── hig.md                       ← Apple HIG
        ├── design-tokens.md             ← Design Tokens
        ├── figma-mcp-commands.md        ← Figma MCP Commands
        └── fontawesome-icons.md         ← FontAwesome Icon Mapping (NEW)</code></pre>
    <h4>🔧 วิธีสร้าง (copy-paste ใน Terminal)</h4>
    <ol>
      <li>สร้างโฟลเดอร์:</li>
    </ol>
    <pre style="background:rgba(255,255,255,0.05); border-radius:8px; padding:12px; margin:8px 0;"><code style="color:#a6e3a1; background:none; border:none;">mkdir -p ~/.claude/commands/references</code></pre>
    <ol start="2">
      <li>
        <strong>ดาวน์โหลดไฟล์ Skill ทั้งหมดจาก Google Drive:</strong><br>
        <a href="https://drive.google.com/file/d/1u-ugwdx8_MehGtaBwIf-HalmIo1DfpJs/view?usp=sharing" target="_blank" style="display:inline-flex; align-items:center; gap:8px; margin:10px 0; padding:12px 20px; background:linear-gradient(135deg,#a259ff,#7b2edd); color:white; text-decoration:none; border-radius:10px; font-weight:700; font-size:14px; transition:opacity 0.15s;">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
          ดาวน์โหลด Skill Files จาก Google Drive
        </a><br>
        <span style="font-size:12.5px; color:rgba(255,255,255,0.5);">ดาวน์โหลดแล้ว unzip → copy ไฟล์ทั้งหมดไปวางใน path ข้างบน</span>
      </li>
      <li>หรือสร้างไฟล์เอง โดย copy เนื้อหาจาก <strong>Section 11</strong> ด้านล่าง แล้ว save เป็น <code>.md</code></li>
    </ol>
    <div style="margin-top:16px; padding:12px 16px; background:rgba(162,89,255,0.15); border-radius:8px; font-size:13.5px;">
      <strong>💡 Tip:</strong> ไฟล์เหล่านี้ไม่ต้องแก้บ่อย ติดตั้งครั้งเดียวใช้ได้ตลอด — ทีมสามารถเพิ่ม/แก้ reference ใหม่ได้ตามต้องการ
    </div>
  </div>
</section>

<!-- ════════════════════ 11. REFERENCE FILES ════════════════════ -->
<section class="section" id="sec11">
  <h2><span class="num" style="background:#0d99ff;">11</span> Reference Files ทั้งหมด</h2>
  <p class="section-subtitle">เนื้อหาครบทุกไฟล์ — copy ไปสร้างได้เลย</p>

  <div class="info-box note">
    <span class="icon">📋</span>
    <div>กดเปิดแต่ละไฟล์ → copy เนื้อหาทั้งหมด → สร้างไฟล์ <code>.md</code> ตาม path ที่ระบุ<br>
    หรือขอไฟล์จากคนในทีมที่ set up ไว้แล้วได้เลย</div>
  </div>

  <!-- ─── ux-principles.md ─── -->
  <details>
    <summary><span style="color:var(--green);">📗</span> ux-principles.md — UX Principles (Nielsen's + Laws of UX + Gestalt)</summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot ref"></span> ~/.claude/commands/references/ux-principles.md</div>

      <h4>Nielsen's 10 Usability Heuristics</h4>

      <h5>1. Visibility of System Status</h5>
      <p>ระบบควรแจ้งให้ผู้ใช้ทราบสถานะอยู่เสมอ ผ่าน feedback ที่เหมาะสมและทันเวลา</p>
      <p><strong>ใช้เมื่อ:</strong> ออกแบบ loading states, progress indicators, status badges, toast notifications</p>
      <ul>
        <li>ทุก action ที่ใช้เวลา > 1 วินาที ต้องมี loading indicator</li>
        <li>ระบุ loading pattern: skeleton, spinner, หรือ progress bar</li>
        <li>ระบุ success/error feedback สำหรับทุก form submission</li>
      </ul>

      <h5>2. Match Between System and the Real World</h5>
      <p>ใช้ภาษาและแนวคิดที่ผู้ใช้คุ้นเคย ไม่ใช้ศัพท์เทคนิคภายใน</p>
      <ul>
        <li>ระบุ copy/text ที่ใช้ในแต่ละ component</li>
        <li>ใช้ icon ที่เป็นมาตรฐานสากล</li>
      </ul>

      <h5>3. User Control and Freedom</h5>
      <p>ให้ทางออกฉุกเฉิน (emergency exit) เสมอ — undo, redo, cancel, back</p>
      <ul>
        <li>ทุก modal ต้องมีปุ่ม close</li>
        <li>Destructive actions ต้องมี confirmation dialog</li>
        <li>Forms ต้อง save draft อัตโนมัติ หรือเตือนก่อน discard</li>
      </ul>

      <h5>4. Consistency and Standards</h5>
      <p>ปฏิบัติตาม platform conventions — อย่าสร้างสิ่งใหม่โดยไม่จำเป็น</p>
      <ul>
        <li>ระบุ design system ที่ใช้</li>
        <li>ใช้ component ที่มีอยู่ใน design system ก่อน</li>
      </ul>

      <h5>5. Error Prevention</h5>
      <p>ป้องกันข้อผิดพลาดก่อนที่จะเกิด ดีกว่าใช้ error message</p>
      <ul>
        <li>ระบุ inline validation สำหรับทุก input field</li>
        <li>ระบุ disabled states เมื่อ action ยังทำไม่ได้</li>
        <li>ระบุ input masks และ constraints (max length, format)</li>
      </ul>

      <h5>6. Recognition Rather Than Recall</h5>
      <p>ลด memory load — แสดงตัวเลือก, actions, ข้อมูลที่ต้องการให้เห็น</p>

      <h5>7. Flexibility and Efficiency of Use</h5>
      <p>รองรับทั้ง novice และ expert users — shortcuts, customization</p>

      <h5>8. Aesthetic and Minimalist Design</h5>
      <p>แสดงเฉพาะข้อมูลที่จำเป็น — จำกัด primary action ได้แค่ 1 ต่อหน้าจอ</p>

      <h5>9. Help Users Recognize, Diagnose, and Recover from Errors</h5>
      <p>Error messages ต้อง: (1) บอกว่าเกิดอะไร (2) เสนอวิธีแก้</p>

      <h5>10. Help and Documentation</h5>
      <p>ให้ความช่วยเหลือเมื่อจำเป็น — tooltips, onboarding, contextual help</p>

      <h4>Laws of UX</h4>
      <table>
        <thead><tr><th>Law</th><th>หลักการ</th><th>Application in Design</th></tr></thead>
        <tbody>
          <tr><td><strong>Fitts's Law</strong></td><td>เวลาเข้าถึง target ขึ้นกับระยะทาง+ขนาด</td><td>Primary CTA: min 48×48dp (Android), 44×44pt (iOS) ปุ่มสำคัญวางใกล้ thumb zone</td></tr>
          <tr><td><strong>Hick's Law</strong></td><td>เวลาตัดสินใจเพิ่มตามจำนวนตัวเลือก</td><td>Nav items ไม่เกิน 5-7, Action buttons: 1 primary + 1-2 secondary</td></tr>
          <tr><td><strong>Jakob's Law</strong></td><td>ผู้ใช้คาดหวังว่าจะทำงานเหมือนที่อื่น</td><td>ใช้ standard patterns (hamburger, tab bar, pull-to-refresh)</td></tr>
          <tr><td><strong>Miller's Law</strong></td><td>คนจำข้อมูลได้ประมาณ 7±2 ชิ้น</td><td>Chunk ข้อมูลเป็นกลุ่ม, section headers ทุก 5-7 items</td></tr>
          <tr><td><strong>Doherty Threshold</strong></td><td>ระบบต้องตอบสนองภายใน 400ms</td><td>Skeleton screens, animations ไม่เกิน 300ms</td></tr>
          <tr><td><strong>Von Restorff</strong></td><td>สิ่งที่แตกต่างจะจำได้ดีกว่า</td><td>Primary CTA ต้องมีสี+ขนาดแตกต่างจาก secondary</td></tr>
          <tr><td><strong>Postel's Law</strong></td><td>รับ input กว้าง, output เข้มงวด</td><td>ยอมรับ input หลายรูปแบบ แสดงผลในรูปแบบมาตรฐาน</td></tr>
          <tr><td><strong>Peak-End Rule</strong></td><td>คนจำจาก peak moment + ending</td><td>Success state น่าจดจำ, completion screen มี next step</td></tr>
        </tbody>
      </table>

      <h4>Gestalt Principles</h4>
      <table>
        <thead><tr><th>Principle</th><th>หลักการ</th><th>Spec Application</th></tr></thead>
        <tbody>
          <tr><td><strong>Proximity</strong></td><td>สิ่งใกล้กัน = กลุ่มเดียว</td><td>Spacing ระหว่าง groups > spacing ภายใน group</td></tr>
          <tr><td><strong>Similarity</strong></td><td>สิ่งเหมือนกัน = กลุ่มเดียว</td><td>Consistent styling สำหรับ components หน้าที่เหมือนกัน</td></tr>
          <tr><td><strong>Continuity</strong></td><td>สายตาตามแนวเส้น</td><td>จัด elements ให้ alignment ใช้ grid system</td></tr>
          <tr><td><strong>Closure</strong></td><td>สมองเติมเต็มรูปร่าง</td><td>ใช้ card patterns, containers จัดกลุ่มข้อมูล</td></tr>
          <tr><td><strong>Common Region</strong></td><td>สิ่งในพื้นที่เดียว = กลุ่มเดียว</td><td>ใช้ background color, cards, dividers แบ่งกลุ่ม</td></tr>
        </tbody>
      </table>
    </div>
  </details>

  <!-- ─── hig.md ─── -->
  <details>
    <summary><span style="color:var(--blue);">📘</span> hig.md — Apple Human Interface Guidelines</summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot ref"></span> ~/.claude/commands/references/hig.md</div>

      <h4>Design Principles (Apple)</h4>
      <ol>
        <li><strong>Aesthetic Integrity</strong> — ความสวยงามสอดคล้องกับฟังก์ชัน</li>
        <li><strong>Consistency</strong> — ใช้ system-provided components</li>
        <li><strong>Direct Manipulation</strong> — interact กับ content โดยตรง (gestures)</li>
        <li><strong>Feedback</strong> — ตอบสนองทุก action ด้วย visual/haptic</li>
        <li><strong>Metaphors</strong> — ใช้สิ่งที่คุ้นเคยในโลกจริง</li>
        <li><strong>User Control</strong> — ให้ผู้ใช้ควบคุม</li>
      </ol>

      <h4>iOS Typography (SF Pro)</h4>
      <table>
        <thead><tr><th>Style</th><th>Weight</th><th>Size</th><th>Leading</th></tr></thead>
        <tbody>
          <tr><td>Large Title</td><td>Bold</td><td>34pt</td><td>41pt</td></tr>
          <tr><td>Title 1</td><td>Bold</td><td>28pt</td><td>34pt</td></tr>
          <tr><td>Title 2</td><td>Bold</td><td>22pt</td><td>28pt</td></tr>
          <tr><td>Title 3</td><td>Semibold</td><td>20pt</td><td>25pt</td></tr>
          <tr><td>Headline</td><td>Semibold</td><td>17pt</td><td>22pt</td></tr>
          <tr><td>Body</td><td>Regular</td><td>17pt</td><td>22pt</td></tr>
          <tr><td>Callout</td><td>Regular</td><td>16pt</td><td>21pt</td></tr>
          <tr><td>Subheadline</td><td>Regular</td><td>15pt</td><td>20pt</td></tr>
          <tr><td>Footnote</td><td>Regular</td><td>13pt</td><td>18pt</td></tr>
          <tr><td>Caption 1</td><td>Regular</td><td>12pt</td><td>16pt</td></tr>
          <tr><td>Caption 2</td><td>Regular</td><td>11pt</td><td>13pt</td></tr>
        </tbody>
      </table>

      <h4>iOS System Colors</h4>
      <table>
        <thead><tr><th>Color</th><th>Light</th><th>Dark</th><th>Usage</th></tr></thead>
        <tbody>
          <tr><td>systemBlue</td><td>#007AFF</td><td>#0A84FF</td><td>Links, tappable</td></tr>
          <tr><td>systemGreen</td><td>#34C759</td><td>#30D158</td><td>Success</td></tr>
          <tr><td>systemRed</td><td>#FF3B30</td><td>#FF453A</td><td>Destructive, error</td></tr>
          <tr><td>systemOrange</td><td>#FF9500</td><td>#FF9F0A</td><td>Warnings</td></tr>
          <tr><td>label</td><td>#000000</td><td>#FFFFFF</td><td>Primary text</td></tr>
          <tr><td>secondaryLabel</td><td>#3C3C43 60%</td><td>#EBEBF5 60%</td><td>Secondary text</td></tr>
          <tr><td>systemBackground</td><td>#FFFFFF</td><td>#000000</td><td>Primary bg</td></tr>
          <tr><td>secondarySystemBg</td><td>#F2F2F7</td><td>#1C1C1E</td><td>Grouped bg</td></tr>
        </tbody>
      </table>

      <h4>Layout &amp; Spacing</h4>
      <table>
        <thead><tr><th>Device</th><th>Margin</th><th>Content Width</th></tr></thead>
        <tbody>
          <tr><td>iPhone SE</td><td>16pt</td><td>343pt</td></tr>
          <tr><td>iPhone 15</td><td>16pt</td><td>361pt</td></tr>
          <tr><td>iPhone 15 Pro Max</td><td>16pt</td><td>398pt</td></tr>
        </tbody>
      </table>
      <p><strong>Standard Spacing:</strong> 4pt, 8pt, 12pt, 16pt, 20pt, 24pt, 32pt (base unit: 8pt)</p>

      <h4>Key Components</h4>
      <table>
        <thead><tr><th>Component</th><th>Size</th><th>Notes</th></tr></thead>
        <tbody>
          <tr><td>Navigation Bar</td><td>44pt (compact) / 96pt (large title)</td><td>Large Title: 34pt Bold</td></tr>
          <tr><td>Tab Bar</td><td>49pt (iPhone)</td><td>2-5 items, icon 25×25pt</td></tr>
          <tr><td>Button (Primary)</td><td>50pt height, 12pt radius</td><td>Bordered Prominent</td></tr>
          <tr><td>Text Field</td><td>36pt height, 10pt radius</td><td>tertiarySystemFill bg</td></tr>
          <tr><td>List Row</td><td>44pt minimum height</td><td>16pt leading/trailing padding</td></tr>
          <tr><td>Sheet</td><td>10pt corner radius</td><td>Grabber: 36×5pt centered</td></tr>
        </tbody>
      </table>

      <h4>Accessibility</h4>
      <ul>
        <li>Touch target: <strong>44pt × 44pt</strong> minimum</li>
        <li>Text contrast: <strong>4.5:1</strong> minimum (AA)</li>
        <li>Large text (≥18pt): <strong>3:1</strong></li>
        <li>ทุก interactive element ต้องมี accessibility label</li>
        <li>รองรับ Dynamic Type + Reduce Motion</li>
      </ul>
    </div>
  </details>

  <!-- ─── material-design.md ─── -->
  <details>
    <summary><span style="color:var(--green);">📗</span> material-design.md — Material Design 3 (M3)</summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot ref"></span> ~/.claude/commands/references/material-design.md</div>

      <h4>M3 Typography (Roboto)</h4>
      <table>
        <thead><tr><th>Style</th><th>Weight</th><th>Size</th><th>Line Height</th></tr></thead>
        <tbody>
          <tr><td>Display Large</td><td>400</td><td>57sp</td><td>64sp</td></tr>
          <tr><td>Display Medium</td><td>400</td><td>45sp</td><td>52sp</td></tr>
          <tr><td>Headline Large</td><td>400</td><td>32sp</td><td>40sp</td></tr>
          <tr><td>Headline Medium</td><td>400</td><td>28sp</td><td>36sp</td></tr>
          <tr><td>Title Large</td><td>400</td><td>22sp</td><td>28sp</td></tr>
          <tr><td>Title Medium</td><td>500</td><td>16sp</td><td>24sp</td></tr>
          <tr><td>Body Large</td><td>400</td><td>16sp</td><td>24sp</td></tr>
          <tr><td>Body Medium</td><td>400</td><td>14sp</td><td>20sp</td></tr>
          <tr><td>Body Small</td><td>400</td><td>12sp</td><td>16sp</td></tr>
          <tr><td>Label Large</td><td>500</td><td>14sp</td><td>20sp</td></tr>
          <tr><td>Label Medium</td><td>500</td><td>12sp</td><td>16sp</td></tr>
        </tbody>
      </table>

      <h4>M3 Color Roles</h4>
      <table>
        <thead><tr><th>Role</th><th>Light</th><th>Dark</th><th>Usage</th></tr></thead>
        <tbody>
          <tr><td>Primary</td><td>seed color</td><td>lighter seed</td><td>Key actions</td></tr>
          <tr><td>Primary Container</td><td>Very light primary</td><td>Muted dark</td><td>Filled buttons bg</td></tr>
          <tr><td>Surface</td><td>#FFFBFE</td><td>#1C1B1F</td><td>Page backgrounds</td></tr>
          <tr><td>On Surface</td><td>#1C1B1F</td><td>#E6E1E5</td><td>Primary text</td></tr>
          <tr><td>Outline</td><td>#79747E</td><td>#938F99</td><td>Borders</td></tr>
          <tr><td>Error</td><td>#B3261E</td><td>#F2B8B5</td><td>Error states</td></tr>
        </tbody>
      </table>

      <h4>Shape (Corner Radius)</h4>
      <table>
        <thead><tr><th>Shape</th><th>Radius</th><th>Usage</th></tr></thead>
        <tbody>
          <tr><td>Extra Small</td><td>4dp</td><td>Chips</td></tr>
          <tr><td>Small</td><td>8dp</td><td>Buttons, text fields</td></tr>
          <tr><td>Medium</td><td>12dp</td><td>Cards, dialogs</td></tr>
          <tr><td>Large</td><td>16dp</td><td>FABs, large cards</td></tr>
          <tr><td>Extra Large</td><td>28dp</td><td>Bottom sheets</td></tr>
          <tr><td>Full</td><td>50%</td><td>Circular elements</td></tr>
        </tbody>
      </table>

      <h4>Responsive Grid</h4>
      <table>
        <thead><tr><th>Window Class</th><th>Width</th><th>Columns</th><th>Margins</th></tr></thead>
        <tbody>
          <tr><td>Compact</td><td>&lt; 600dp</td><td>4</td><td>16dp</td></tr>
          <tr><td>Medium</td><td>600-839dp</td><td>8</td><td>24dp</td></tr>
          <tr><td>Expanded</td><td>840-1199dp</td><td>12</td><td>24dp</td></tr>
        </tbody>
      </table>

      <h4>Key Components</h4>
      <table>
        <thead><tr><th>Component</th><th>Height</th><th>Radius</th><th>Notes</th></tr></thead>
        <tbody>
          <tr><td>Filled Button</td><td>40dp</td><td>20dp (full)</td><td>Primary CTA</td></tr>
          <tr><td>Outlined Button</td><td>40dp</td><td>20dp</td><td>Secondary</td></tr>
          <tr><td>FAB</td><td>56dp</td><td>16dp</td><td>Primary floating action</td></tr>
          <tr><td>Text Field</td><td>56dp</td><td>varies</td><td>Filled or Outlined</td></tr>
          <tr><td>Card</td><td>varies</td><td>12dp</td><td>16dp padding all sides</td></tr>
          <tr><td>Dialog</td><td>varies</td><td>28dp</td><td>Width: 280-560dp</td></tr>
          <tr><td>Bottom Sheet</td><td>varies</td><td>28dp top</td><td>Handle: 32×4dp</td></tr>
          <tr><td>Navigation Bar</td><td>80dp</td><td>—</td><td>3-5 items</td></tr>
        </tbody>
      </table>

      <h4>Accessibility</h4>
      <ul>
        <li>Touch target: <strong>48dp × 48dp</strong> minimum</li>
        <li>Recommended: <strong>56dp × 56dp</strong> สำหรับ primary actions</li>
        <li>Normal text contrast: <strong>4.5:1</strong></li>
        <li>Large text (≥18sp): <strong>3:1</strong></li>
      </ul>
    </div>
  </details>

  <!-- ─── design-tokens.md ─── -->
  <details>
    <summary><span style="color:var(--orange);">📙</span> design-tokens.md — Design Tokens Reference</summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot ref"></span> ~/.claude/commands/references/design-tokens.md</div>

      <h4>Token Naming Convention</h4>
      <p>ใช้รูปแบบ: <code>{category}-{property}-{variant}-{state}</code></p>
      <pre><code>color-primary-default          → #6200EE
color-text-primary             → #1A1A1A
spacing-md                     → 16px
font-size-body-md              → 14px
radius-md                      → 8px
shadow-md                      → 0 4px 8px rgba(0,0,0,0.12)</code></pre>

      <h4>Color Tokens</h4>
      <table>
        <thead><tr><th>Token</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td>color-primary</td><td>Brand primary</td></tr>
          <tr><td>color-secondary</td><td>Brand secondary</td></tr>
          <tr><td>color-error / warning / success / info</td><td>Semantic colors</td></tr>
          <tr><td>color-bg-primary / secondary / tertiary</td><td>Surface colors</td></tr>
          <tr><td>color-text-primary / secondary / disabled / link</td><td>Text colors</td></tr>
          <tr><td>color-border-default / focus / error</td><td>Border colors</td></tr>
        </tbody>
      </table>

      <h4>Typography Tokens</h4>
      <table>
        <thead><tr><th>Token</th><th>Value</th></tr></thead>
        <tbody>
          <tr><td>font-family-primary</td><td>"Inter", "SF Pro", "Roboto"</td></tr>
          <tr><td>font-size-xs / sm / md / lg / xl / 2xl / 3xl / 4xl</td><td>11 / 12 / 14 / 16 / 20 / 24 / 32 / 40 px</td></tr>
          <tr><td>font-weight-regular / medium / semibold / bold</td><td>400 / 500 / 600 / 700</td></tr>
          <tr><td>line-height-tight / normal / relaxed</td><td>1.25 / 1.5 / 1.75</td></tr>
        </tbody>
      </table>

      <h4>Spacing Tokens (4px base)</h4>
      <table>
        <thead><tr><th>Token</th><th>Value</th><th>Usage</th></tr></thead>
        <tbody>
          <tr><td>spacing-1</td><td>4px</td><td>Icon gap</td></tr>
          <tr><td>spacing-2</td><td>8px</td><td>Inline element gap</td></tr>
          <tr><td>spacing-3</td><td>12px</td><td>List item padding</td></tr>
          <tr><td>spacing-4</td><td>16px</td><td>Content padding, card padding</td></tr>
          <tr><td>spacing-6</td><td>24px</td><td>Section gaps</td></tr>
          <tr><td>spacing-8</td><td>32px</td><td>Large section gaps</td></tr>
          <tr><td>spacing-10</td><td>40px</td><td>Page section breaks</td></tr>
        </tbody>
      </table>

      <h4>Radius / Shadow / Motion Tokens</h4>
      <table>
        <thead><tr><th>Category</th><th>Token</th><th>Value</th></tr></thead>
        <tbody>
          <tr><td>Radius</td><td>radius-sm / md / lg / xl / full</td><td>4 / 8 / 12 / 16 / 9999 px</td></tr>
          <tr><td>Shadow</td><td>shadow-xs / sm / md / lg / xl</td><td>subtle → strong</td></tr>
          <tr><td>Motion</td><td>duration-fast / normal / slow</td><td>200 / 300 / 500 ms</td></tr>
          <tr><td>Easing</td><td>easing-default / enter / exit</td><td>ease-in-out / ease-out / ease-in</td></tr>
        </tbody>
      </table>

      <h4>Figma Integration</h4>
      <ul>
        <li><strong>Figma Variables:</strong> สร้าง Color, Number, String variables ตาม token — จัดเป็น Collections + modes (Light/Dark)</li>
        <li><strong>Figma Styles:</strong> สร้าง Text Styles, Color Styles, Effect Styles ใช้ชื่อตาม token naming</li>
        <li><strong>Auto Layout:</strong> ใช้ spacing tokens ใน item spacing + padding</li>
      </ul>
    </div>
  </details>

  <!-- ─── fontawesome-icons.md ─── -->
  <details>
    <summary><span style="color:#1bc47d;">📗</span> fontawesome-icons.md — FontAwesome Icons Reference <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot ref"></span> ~/.claude/commands/references/fontawesome-icons.md</div>
      <div class="info-box note" style="margin:12px 0;">
        <span class="icon">💡</span>
        <div><strong>ทำไมต้องใช้ FontAwesome?</strong> MCP ไม่สามารถสร้าง vector icon ได้โดยตรง ดังนั้นใช้ text placeholder + ตั้งชื่อ layer เป็น FA icon name แล้ว Dev map เป็น component จริงตอน implement</div>
      </div>

      <h4>Naming Convention</h4>
      <pre><code><span class="cm">// Layer name format:</span>  icon/fa-{icon-name}
<span class="cm">// ตัวอย่าง:</span>  icon/fa-calendar, icon/fa-user, icon/fa-bell
<span class="cm">// Dev map เป็น:</span>  &lt;FontAwesomeIcon icon="fa-{name}" /&gt;</code></pre>

      <h4>Navigation Icons</h4>
      <table>
        <thead><tr><th>Icon Name</th><th>Placeholder</th><th>Usage</th></tr></thead>
        <tbody>
          <tr><td><code>fa-home</code></td><td>⌂</td><td>Home / หน้าแรก</td></tr>
          <tr><td><code>fa-arrow-left</code></td><td>←</td><td>Back / ย้อนกลับ</td></tr>
          <tr><td><code>fa-bars</code></td><td>☰</td><td>Menu / เมนู</td></tr>
          <tr><td><code>fa-xmark</code></td><td>✕</td><td>Close / ปิด</td></tr>
          <tr><td><code>fa-chevron-down</code></td><td>▾</td><td>Dropdown</td></tr>
          <tr><td><code>fa-ellipsis</code></td><td>⋯</td><td>More options</td></tr>
        </tbody>
      </table>

      <h4>Action Icons</h4>
      <table>
        <thead><tr><th>Icon Name</th><th>Placeholder</th><th>Usage</th></tr></thead>
        <tbody>
          <tr><td><code>fa-plus</code></td><td>+</td><td>Add / เพิ่ม</td></tr>
          <tr><td><code>fa-pen</code></td><td>✎</td><td>Edit / แก้ไข</td></tr>
          <tr><td><code>fa-trash</code></td><td>🗑</td><td>Delete / ลบ</td></tr>
          <tr><td><code>fa-magnifying-glass</code></td><td>⌕</td><td>Search / ค้นหา</td></tr>
          <tr><td><code>fa-share</code></td><td>↗</td><td>Share / แชร์</td></tr>
          <tr><td><code>fa-check</code></td><td>✓</td><td>Confirm / ยืนยัน</td></tr>
        </tbody>
      </table>

      <h4>User &amp; Communication Icons</h4>
      <table>
        <thead><tr><th>Icon Name</th><th>Placeholder</th><th>Usage</th></tr></thead>
        <tbody>
          <tr><td><code>fa-user</code></td><td>👤</td><td>User / ผู้ใช้</td></tr>
          <tr><td><code>fa-gear</code></td><td>⚙</td><td>Settings / ตั้งค่า</td></tr>
          <tr><td><code>fa-bell</code></td><td>🔔</td><td>Notification / แจ้งเตือน</td></tr>
          <tr><td><code>fa-envelope</code></td><td>✉</td><td>Email / อีเมล</td></tr>
          <tr><td><code>fa-comment</code></td><td>💬</td><td>Chat / แชท</td></tr>
          <tr><td><code>fa-paper-plane</code></td><td>➤</td><td>Send / ส่ง</td></tr>
        </tbody>
      </table>

      <h4>Content, Calendar &amp; Status Icons</h4>
      <table>
        <thead><tr><th>Icon Name</th><th>Placeholder</th><th>Usage</th></tr></thead>
        <tbody>
          <tr><td><code>fa-calendar</code></td><td>📅</td><td>Calendar / ปฏิทิน</td></tr>
          <tr><td><code>fa-clock</code></td><td>🕐</td><td>Time / เวลา</td></tr>
          <tr><td><code>fa-image</code></td><td>🖼</td><td>Image / รูปภาพ</td></tr>
          <tr><td><code>fa-circle-check</code></td><td>✅</td><td>Success / สำเร็จ</td></tr>
          <tr><td><code>fa-circle-xmark</code></td><td>❌</td><td>Error / ผิดพลาด</td></tr>
          <tr><td><code>fa-circle-exclamation</code></td><td>⚠</td><td>Warning / เตือน</td></tr>
          <tr><td><code>fa-star</code></td><td>★</td><td>Favorite / ชอบ</td></tr>
          <tr><td><code>fa-heart</code></td><td>♥</td><td>Like / ถูกใจ</td></tr>
          <tr><td><code>fa-cart-shopping</code></td><td>🛒</td><td>Cart / ตะกร้า</td></tr>
          <tr><td><code>fa-location-dot</code></td><td>📍</td><td>Location / ตำแหน่ง</td></tr>
        </tbody>
      </table>

      <h4>Size Mapping</h4>
      <table>
        <thead><tr><th>Token</th><th>Size</th><th>FA Class</th></tr></thead>
        <tbody>
          <tr><td><code>icon.xs</code></td><td>12px</td><td>fa-xs</td></tr>
          <tr><td><code>icon.sm</code></td><td>16px</td><td>fa-sm</td></tr>
          <tr><td><code>icon.md</code></td><td>20px</td><td>— (default)</td></tr>
          <tr><td><code>icon.lg</code></td><td>24px</td><td>fa-lg</td></tr>
          <tr><td><code>icon.xl</code></td><td>32px</td><td>fa-xl</td></tr>
        </tbody>
      </table>

      <h4>Install FontAwesome (for Dev)</h4>
      <pre><code><span class="cm"># React</span>
npm install @fortawesome/fontawesome-svg-core \
  @fortawesome/free-solid-svg-icons \
  @fortawesome/react-fontawesome

<span class="cm"># Usage</span>
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCalendar } from '@fortawesome/free-solid-svg-icons'
&lt;FontAwesomeIcon icon={faCalendar} size="lg" color="#7C5CFC" /&gt;</code></pre>
    </div>
  </details>

  <!-- ─── figma-mcp-commands.md ─── -->
  <details>
    <summary><span style="color:var(--red);">📕</span> figma-mcp-commands.md — Figma MCP Commands Reference <span style="background:#f24822;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">UPDATED</span></summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot ref"></span> ~/.claude/commands/references/figma-mcp-commands.md</div>
      <div class="info-box warn" style="margin:12px 0;">
        <span class="icon">⚠️</span>
        <div><strong>อัปเดตล่าสุด:</strong> ลบ commands ที่ไม่มีจริง (insert_child, create_ellipse, set_auto_layout, load_font_async ฯลฯ) + เพิ่ม commands ใหม่ 20+ ตัว + เพิ่ม Figma Remote MCP</div>
      </div>

      <h4>MCP Servers 2 ตัว</h4>
      <table>
        <thead><tr><th>Server</th><th>ประเภท</th><th>หน้าที่</th></tr></thead>
        <tbody>
          <tr><td><strong>TalkToFigma</strong></td><td>Local Plugin (stdio)</td><td>สร้าง/แก้ไข/ลบ elements ใน Figma โดยตรง</td></tr>
          <tr><td><strong>figma</strong></td><td>Remote (Figma API)</td><td>อ่าน design, screenshot, generate code, diagrams</td></tr>
        </tbody>
      </table>

      <h4>Document &amp; Selection (TalkToFigma)</h4>
      <table>
        <thead><tr><th>Command</th><th>Parameters</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><code>get_document_info</code></td><td>—</td><td>ดูข้อมูล document (pages, frames)</td></tr>
          <tr><td><code>get_selection</code></td><td>—</td><td>ดู elements ที่ถูกเลือก (basic info)</td></tr>
          <tr><td><code>read_my_design</code></td><td>—</td><td>ดูรายละเอียดทั้งหมดของ selection (all node details)</td></tr>
          <tr><td><code>get_node_info</code></td><td>nodeId</td><td>ดูรายละเอียด element ตาม ID</td></tr>
          <tr><td><code>get_nodes_info</code></td><td>nodeIds[]</td><td>ดูหลาย elements พร้อมกัน</td></tr>
          <tr><td><code>scan_text_nodes</code></td><td>nodeId</td><td>หา text nodes ทั้งหมดใน node</td></tr>
          <tr><td><code>scan_nodes_by_types</code></td><td>nodeId, types[]</td><td>หา child nodes ตาม type เช่น ['COMPONENT', 'FRAME']</td></tr>
          <tr><td><code>get_styles</code></td><td>—</td><td>ดู styles ใน document</td></tr>
          <tr><td><code>export_node_as_image</code></td><td>nodeId, format?, scale?</td><td>Export เป็น PNG/JPG/SVG/PDF</td></tr>
          <tr><td><code>set_focus</code></td><td>nodeId</td><td>เลือก node + scroll viewport ไปหา</td></tr>
          <tr><td><code>set_selections</code></td><td>nodeIds[]</td><td>เลือกหลาย nodes + scroll ไปแสดง</td></tr>
        </tbody>
      </table>

      <h4>Creation Tools</h4>
      <table>
        <thead><tr><th>Command</th><th>Key Parameters</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><code>create_frame</code></td><td>x, y, w, h, <strong>name?, parentId?, fillColor?, layoutMode?, itemSpacing?, padding*?, alignment?</strong></td><td>สร้าง frame (รองรับ auto layout + สี + parentId ในคำสั่งเดียว)</td></tr>
          <tr><td><code>create_rectangle</code></td><td>x, y, w, h, name?, parentId?</td><td>สร้างสี่เหลี่ยม</td></tr>
          <tr><td><code>create_text</code></td><td>x, y, text, <strong>name?, parentId?, fontSize?, fontWeight?, fontColor?</strong></td><td>สร้าง text (ตั้ง font ตอนสร้างเท่านั้น)</td></tr>
          <tr><td><code>clone_node</code></td><td>nodeId, x?, y?</td><td>สำเนา element (ตั้งตำแหน่งใหม่ได้)</td></tr>
          <tr><td><code>delete_node</code></td><td>nodeId</td><td>ลบ element</td></tr>
          <tr><td><code>delete_multiple_nodes</code></td><td>nodeIds[]</td><td>ลบหลาย elements พร้อมกัน</td></tr>
        </tbody>
      </table>

      <h4>Modification Tools</h4>
      <table>
        <thead><tr><th>Command</th><th>Parameters</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><code>move_node</code></td><td>nodeId, x, y</td><td>ย้าย element</td></tr>
          <tr><td><code>resize_node</code></td><td>nodeId, width, height</td><td>ปรับขนาด (ค่าต้อง > 0)</td></tr>
          <tr><td><code>set_fill_color</code></td><td>nodeId, r, g, b, a?</td><td>ตั้งสีพื้น (<strong>RGBA 0-1</strong>) ใช้ได้กับ Text และ Frame</td></tr>
          <tr><td><code>set_stroke_color</code></td><td>nodeId, r, g, b, a?, weight?</td><td>ตั้งสีเส้นขอบ + ความหนา</td></tr>
          <tr><td><code>set_corner_radius</code></td><td>nodeId, radius, corners?</td><td>ตั้ง corner radius (corners = [TL,TR,BR,BL] booleans)</td></tr>
        </tbody>
      </table>

      <h4>Auto Layout Tools (แยก 5 คำสั่ง — ไม่มี set_auto_layout รวม)</h4>
      <table>
        <thead><tr><th>Command</th><th>Parameters</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><code>set_layout_mode</code></td><td>nodeId, layoutMode, layoutWrap?</td><td>NONE / HORIZONTAL / VERTICAL</td></tr>
          <tr><td><code>set_padding</code></td><td>nodeId, paddingTop/Right/Bottom/Left?</td><td>ตั้ง padding</td></tr>
          <tr><td><code>set_axis_align</code></td><td>nodeId, primaryAxisAlignItems?, counterAxisAlignItems?</td><td>MIN / CENTER / MAX / SPACE_BETWEEN</td></tr>
          <tr><td><code>set_layout_sizing</code></td><td>nodeId, layoutSizingH?, layoutSizingV?</td><td>FIXED / HUG / FILL</td></tr>
          <tr><td><code>set_item_spacing</code></td><td>nodeId, itemSpacing?, counterAxisSpacing?</td><td>spacing ระหว่าง children</td></tr>
        </tbody>
      </table>
      <div class="info-box note" style="margin:8px 0;">
        <span class="icon">💡</span>
        <div><strong>ทางลัด:</strong> <code>create_frame</code> รองรับตั้ง auto layout ทั้งหมดพร้อมสร้างได้เลย (layoutMode, itemSpacing, padding, alignment, sizing)</div>
      </div>

      <h4>Text Tools</h4>
      <table>
        <thead><tr><th>Command</th><th>Parameters</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><code>set_text_content</code></td><td>nodeId, text</td><td>เปลี่ยน text content</td></tr>
          <tr><td><code>set_multiple_text_contents</code></td><td>nodeId (parent), text[]</td><td>เปลี่ยน text หลายตัวพร้อมกัน</td></tr>
        </tbody>
      </table>
      <div class="info-box warn" style="margin:8px 0;">
        <span class="icon">⚠️</span>
        <div><strong>ไม่มี:</strong> set_font_name, set_font_size, set_font_weight, load_font_async — ตั้งค่า font ได้ตอน <code>create_text</code> เท่านั้น (fontSize, fontWeight, fontColor)</div>
      </div>

      <h4>Component Tools</h4>
      <table>
        <thead><tr><th>Command</th><th>Parameters</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><code>get_local_components</code></td><td>—</td><td>ดู components ใน file</td></tr>
          <tr><td><code>create_component_instance</code></td><td>componentKey, x, y</td><td>สร้าง instance จาก component</td></tr>
          <tr><td><code>get_instance_overrides</code></td><td>nodeId?</td><td>ดู overrides ของ instance</td></tr>
          <tr><td><code>set_instance_overrides</code></td><td>sourceInstanceId, targetNodeIds[]</td><td>Copy overrides จาก source ไป targets</td></tr>
        </tbody>
      </table>

      <h4>Annotation &amp; Connector Tools</h4>
      <table>
        <thead><tr><th>Command</th><th>Parameters</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><code>get_annotations</code></td><td>nodeId</td><td>ดู annotations ของ node</td></tr>
          <tr><td><code>set_annotation</code></td><td>nodeId, labelMarkdown</td><td>สร้าง/อัปเดต annotation</td></tr>
          <tr><td><code>set_multiple_annotations</code></td><td>nodeId, annotations[]</td><td>สร้างหลาย annotations พร้อมกัน</td></tr>
          <tr><td><code>create_connections</code></td><td>connections[]</td><td>สร้างเส้นเชื่อมระหว่าง nodes</td></tr>
          <tr><td><code>set_default_connector</code></td><td>connectorId?</td><td>ตั้ง connector style</td></tr>
        </tbody>
      </table>

      <h4>Figma Remote MCP (อ่าน design จากไฟล์)</h4>
      <table>
        <thead><tr><th>Command</th><th>Parameters</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><code>get_screenshot</code></td><td>fileKey, nodeId</td><td>ถ่ายภาพหน้าจอของ node</td></tr>
          <tr><td><code>get_design_context</code></td><td>fileKey, nodeId</td><td>อ่าน design + generate UI code</td></tr>
          <tr><td><code>get_metadata</code></td><td>fileKey, nodeId</td><td>ดู structure ในรูปแบบ XML</td></tr>
          <tr><td><code>get_variable_defs</code></td><td>fileKey, nodeId</td><td>ดู design variables</td></tr>
          <tr><td><code>generate_diagram</code></td><td>name, mermaidSyntax</td><td>สร้าง diagram ใน FigJam จาก Mermaid.js</td></tr>
        </tbody>
      </table>

      <h4>Common Patterns (อัปเดตแล้ว)</h4>
      <h5>Pattern: สร้าง iPhone Frame (คำสั่งเดียว)</h5>
      <pre><code>create_frame({
  name: "Login Screen",
  x: 0, y: 0, width: 393, height: 852,
  fillColor: {r: 1, g: 1, b: 1},
  layoutMode: "VERTICAL",
  paddingRight: 16, paddingLeft: 16,
  primaryAxisAlignItems: "MIN",
  layoutSizingHorizontal: "FIXED",
  layoutSizingVertical: "FIXED"
})
set_corner_radius(nodeId, 47)</code></pre>

      <h5>Pattern: สร้าง Button (ใช้ parentId)</h5>
      <pre><code>create_frame({
  name: "Log In Button",
  parentId: "screen-id",           // ใส่เข้า parent เลย
  x: 0, y: 0, width: 361, height: 50,
  fillColor: {r: 0, g: 0.48, b: 1},
  layoutMode: "HORIZONTAL",
  primaryAxisAlignItems: "CENTER",
  counterAxisAlignItems: "CENTER"
})
set_corner_radius(button_id, 12)

create_text({
  text: "Log In",
  x: 0, y: 0,
  fontSize: 17, fontWeight: 700,
  fontColor: {r: 1, g: 1, b: 1},
  parentId: "button-id"            // ใส่เข้า button เลย
})</code></pre>

      <h4>Pattern: Smart Frame Positioning (ป้องกัน Frame ทับกัน) <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></h4>
      <div class="info-box warn" style="margin:8px 0;">
        <span class="icon">⚠️</span>
        <div><strong>สำคัญ:</strong> ก่อนสร้าง frame ใหม่ทุกครั้ง ต้องสแกนตำแหน่ง frame เดิมก่อนเสมอ เพื่อป้องกันการทับซ้อน</div>
      </div>
      <pre><code><span class="cm">// ขั้นตอนที่ 1: สแกน document เพื่อดู frame ที่มีอยู่แล้ว</span>
get_document_info()

<span class="cm">// ขั้นตอนที่ 2: ดูรายละเอียด position/size</span>
get_nodes_info(nodeIds: ["frame-1-id", "frame-2-id", ...])

<span class="cm">// ขั้นตอนที่ 3: คำนวณตำแหน่งใหม่ที่ไม่ทับ</span>
GAP = 100  <span class="cm">// ระยะห่างระหว่าง frames (px)</span>
maxX = max(frame.x + frame.width) <span class="cm">// หา edge ขวาสุด</span>
newFrameX = maxX + GAP
newFrameY = 0

<span class="cm">// ขั้นตอนที่ 4: สร้าง frame ที่ตำแหน่งว่าง</span>
create_frame({ x: newFrameX, y: 0, width: 393, height: 852, ... })</code></pre>
      <table>
        <thead><tr><th>Strategy</th><th>เมื่อไหร่ใช้</th><th>วิธีคำนวณ</th></tr></thead>
        <tbody>
          <tr><td><strong>วางขวา</strong> (Default)</td><td>เรียงแนวนอน</td><td><code>x = maxX + 100</code></td></tr>
          <tr><td><strong>วางล่าง</strong></td><td>เรียงแนวตั้ง</td><td><code>y = maxY + 100</code></td></tr>
          <tr><td><strong>Grid</strong></td><td>หลาย frame (Responsive)</td><td>ทุก 3 frame ขึ้นแถวใหม่</td></tr>
        </tbody>
      </table>

      <h4>Pattern: Icon Placeholder ด้วย FontAwesome <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></h4>
      <div class="info-box note" style="margin:8px 0;">
        <span class="icon">💡</span>
        <div><strong>เนื่องจาก MCP ไม่สามารถสร้าง vector icon ได้</strong> — ให้ใช้ text placeholder + ตั้งชื่อ layer เป็น FontAwesome icon name แทน Dev จะ map ชื่อ layer → FontAwesome component ตอน implement</div>
      </div>
      <pre><code><span class="cm">// ใช้ emoji/symbol placeholder + ตั้งชื่อ layer เป็น FA icon name</span>
create_text({
  text: "📅",              <span class="cm">// placeholder</span>
  name: "icon/fa-calendar", <span class="cm">// → Dev map เป็น &lt;FontAwesomeIcon icon="faCalendar" /&gt;</span>
  fontSize: 20,
  fontColor: {r: 0.42, g: 0.447, b: 0.502},
  parentId: "container-id"
})

<span class="cm">// Naming Convention: icon/fa-{icon-name}</span>
<span class="cm">// ดูรายชื่อ icon ทั้งหมดที่ references/fontawesome-icons.md</span></code></pre>

      <h4>Color Conversion (Hex → Figma RGBA 0-1)</h4>
      <table>
        <thead><tr><th>Color</th><th>Hex</th><th>Figma RGBA</th></tr></thead>
        <tbody>
          <tr><td>systemBlue</td><td>#007AFF</td><td>r=0, g=0.478, b=1</td></tr>
          <tr><td>systemRed</td><td>#FF3B30</td><td>r=1, g=0.231, b=0.188</td></tr>
          <tr><td>systemGreen</td><td>#34C759</td><td>r=0.204, g=0.78, b=0.349</td></tr>
          <tr><td>M3 Primary</td><td>#6750A4</td><td>r=0.404, g=0.314, b=0.643</td></tr>
          <tr><td>White</td><td>#FFFFFF</td><td>r=1, g=1, b=1</td></tr>
          <tr><td>Black</td><td>#000000</td><td>r=0, g=0, b=0</td></tr>
        </tbody>
      </table>
      <pre><code><span class="cm">// Hex to Figma RGBA Formula</span>
r = parseInt(hex.slice(1,3), 16) / 255
g = parseInt(hex.slice(3,5), 16) / 255
b = parseInt(hex.slice(5,7), 16) / 255</code></pre>

      <h4>สิ่งที่ไม่มีใน MCP (ต้องทำใน Figma โดยตรง)</h4>
      <ul>
        <li>สร้าง/ลบ/เปลี่ยนชื่อ Page</li>
        <li>สร้าง Ellipse, Polygon, Star shapes</li>
        <li>Group/Ungroup nodes</li>
        <li>เปลี่ยน font family/style หลังสร้าง text แล้ว</li>
        <li>ตั้ง effects (shadow, blur)</li>
        <li>ตั้ง text decoration, line height, letter spacing</li>
        <li>Rename node</li>
        <li>ใช้ remote components (team library)</li>
      </ul>
    </div>
  </details>

  <!-- ─── Figma-ui-design-spec.md (raw) ─── -->
  <details>
    <summary><span style="color:var(--accent);">⚡</span> figma-ui-design-spec.md — Skill File (ไฟล์หลัก) <span style="background:#a259ff;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">UPDATED</span></summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-ui-design-spec.md</div>
      <div class="info-box warn">
        <span class="icon">📋</span>
        <div>Copy เนื้อหาด้านล่างทั้งหมด แล้ว save เป็นไฟล์ <code>~/.claude/commands/figma-ui-design-spec.md</code></div>
      </div>
      <pre><code>---
name: figma-ui-design-spec
description: "สร้าง UI Design Specification document สำหรับนำไปใช้งานใน Figma
  โดยอ้างอิง Design Principles หลักๆ ได้แก่ Material Design,
  Human Interface Guidelines (Apple), Nielsen's Heuristics, Laws of UX
  และ Custom Design System ของทีม"
---

# Figma UI Design Specification Skill

สร้างเอกสาร UI Design Specification ที่ครบถ้วน อ้างอิงหลักการออกแบบที่ได้มาตรฐาน
พร้อม preview และสร้างหน้าจอจริงใน Figma ได้

## Overall Flow

1. Requirements → 2. Read Design Principles → 3. Preview (React)
→ 4. Iterate → 5. Build in Figma (MCP)

## Step 1: รวบรวม Requirements
ถามข้อมูล: Platform, Screen/Component, User Goal,
Detail Level, Design System, Constraints, Reference Design (Figma URL)

## Step 2: อ่าน Design Principles
- references/ux-principles.md        → อ่านเสมอ
- references/material-design.md      → สำหรับ Android / Web
- references/hig.md                  → สำหรับ iOS / macOS
- references/design-tokens.md        → สำหรับ Custom Design System
- references/figma-mcp-commands.md   → สำหรับ Step 5
- references/fontawesome-icons.md   → FontAwesome Icon Mapping (NEW)
ถ้ามี reference Figma URL → ใช้ get_screenshot / get_design_context อ่านได้

## Step 3: สร้าง Interactive Preview (React .jsx)
Preview ต้องมี: device frame, status bar, ทุก component,
Light/Dark toggle, State switcher, Interactive elements, Spec panel

## Step 4: Iterate จนพอใจ
วนจนกว่าผู้ใช้พอใจ แล้วถาม "พร้อมสร้างใน Figma ไหม?"

## Step 5: สร้างใน Figma ผ่าน MCP
5.1 Connect → 5.2 Prepare → 5.3 Build → 5.4 Verify → 5.5 Annotate

Build: ใช้ parentId ใส่เข้า parent ตอนสร้างได้เลย (ไม่มี insert_child)
create_frame รองรับ auto layout + สี + parentId ในคำสั่งเดียว
ไม่มี set_auto_layout รวม — แยก: set_layout_mode, set_padding,
  set_axis_align, set_layout_sizing, set_item_spacing

## WCAG Color Contrast Checker (บังคับ)
Normal text (&lt; 18pt): 4.5:1 AA / 7:1 AAA
Large text (≥ 18pt bold / ≥ 24pt regular): 3:1 AA / 4.5:1 AAA
UI components &amp; icons: 3:1 AA
ทุกคู่สี text/bg ต้องผ่าน AA ขั้นต่ำ พร้อมระบุค่า ratio ใน spec

## หลักการสำคัญ 10 ข้อ
1. เจาะจงและวัดผลได้
2. อ้างอิง Design Principle
3. Edge Cases
4. Accessibility First
5. WCAG Contrast Verified
6. Platform-Aware
7. Preview First
8. Figma-Ready
9. Use parentId (ไม่มี insert_child)
10. Font ตั้งตอนสร้าง (fontSize, fontWeight, fontColor ตอน create_text เท่านั้น)

## MCP Limitations (ต้องทำใน Figma โดยตรง)
- สร้าง/ลบ/เปลี่ยนชื่อ Page
- สร้าง Ellipse, Polygon, Star
- Group/Ungroup nodes
- เปลี่ยน font หลังสร้าง text
- ตั้ง effects (shadow, blur)
- Rename node</code></pre>
      <div class="info-box note">
        <span class="icon">💡</span>
        <div>นี่เป็นเวอร์ชันย่อ — ไฟล์จริงมีรายละเอียดมากกว่านี้ (WCAG สูตรคำนวณ, Design Spec Templates ฯลฯ) ขอไฟล์เต็มจากคนในทีมที่ set up ไว้แล้ว</div>
      </div>
    </div>
  </details>

  <!-- ─── figma-design-critique.md ─── -->
  <details>
    <summary><span style="color:var(--green);">🔍</span> figma-design-critique.md — Design Critique / Review Skill <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-design-critique.md</div>
      <div class="info-box note">
        <span class="icon">📋</span>
        <div>Copy เนื้อหาด้านล่างทั้งหมด แล้ว save เป็นไฟล์ <code>~/.claude/commands/figma-design-critique.md</code></div>
      </div>

      <h4>Overview</h4>
      <p>วิเคราะห์ design ที่มีอยู่อย่างเป็นระบบ — ให้ feedback เชิงลึกตาม UX principles พร้อมคะแนน 8 มิติ</p>
      <p><strong>Flow:</strong> Capture → Read Principles → Analyze (8 มิติ) → Score → Report → Fix (Optional)</p>

      <h4>8 Dimensions</h4>
      <table>
        <thead><tr><th>มิติ</th><th>Weight</th><th>ตรวจอะไร</th></tr></thead>
        <tbody>
          <tr><td>Visual Hierarchy &amp; Layout</td><td>15%</td><td>Hierarchy, alignment, white space, Gestalt</td></tr>
          <tr><td>Typography</td><td>10%</td><td>Type scale, weight contrast, readability</td></tr>
          <tr><td>Color &amp; Contrast</td><td>15%</td><td>WCAG contrast, palette, semantic colors</td></tr>
          <tr><td>Component Design</td><td>15%</td><td>Platform conventions, hierarchy, states</td></tr>
          <tr><td>Spacing &amp; Consistency</td><td>10%</td><td>Grid system, padding/margin consistency</td></tr>
          <tr><td>UX Heuristics</td><td>20%</td><td>Nielsen's 10 Heuristics ทุกข้อ</td></tr>
          <tr><td>Accessibility</td><td>10%</td><td>Touch targets, color independence, SR</td></tr>
          <tr><td>Edge Cases</td><td>5%</td><td>Empty, loading, error, long text</td></tr>
        </tbody>
      </table>

      <h4>Key Features</h4>
      <ul>
        <li>รับ design จาก Figma URL (screenshot + design context) หรือ selection</li>
        <li>WCAG Color Contrast check ทุกคู่สี (สูตร relative luminance)</li>
        <li>ให้คะแนน 1-10 ทุกมิติ + Weighted Total</li>
        <li>แยก Issues เป็น Critical / Major / Minor</li>
        <li>ทุก issue อ้างอิง principle + มี recommendation</li>
        <li>Optional: แก้ไขตรงใน Figma ผ่าน MCP</li>
      </ul>

      <h4>Trigger Words</h4>
      <p><code>review</code>, <code>critique</code>, <code>วิเคราะห์ design</code>, <code>ตรวจ UI</code>, <code>ให้ feedback</code>, <code>design review</code>, <code>UX audit</code></p>
    </div>
  </details>

  <!-- ─── figma-user-flow.md ─── -->
  <details>
    <summary><span style="color:var(--blue);">🔀</span> figma-user-flow.md — User Flow / IA Skill <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-user-flow.md</div>
      <div class="info-box note">
        <span class="icon">📋</span>
        <div>Copy เนื้อหาด้านล่างทั้งหมด แล้ว save เป็นไฟล์ <code>~/.claude/commands/figma-user-flow.md</code></div>
      </div>

      <h4>Overview</h4>
      <p>ออกแบบ User Flow และ Information Architecture สำหรับ app/web ทั้งระบบ — ไม่ใช่แค่หน้าจอเดียว แต่มองภาพรวมทั้ง journey</p>
      <p><strong>Flow:</strong> Requirements → Read Principles → Map IA → Design Flows → Generate Diagrams → Build in Figma</p>

      <h4>Outputs</h4>
      <table>
        <thead><tr><th>Output</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td>Feature Inventory</td><td>Must Have / Should Have / Could Have</td></tr>
          <tr><td>Content Model</td><td>Entities + relationships</td></tr>
          <tr><td>Screen Map</td><td>Screen hierarchy (Level 0-3)</td></tr>
          <tr><td>Navigation Matrix</td><td>From/To + transition types</td></tr>
          <tr><td>User Flows</td><td>Happy + error paths + decision points</td></tr>
          <tr><td>Flow Diagrams</td><td>Mermaid.js ใน FigJam (generate_diagram)</td></tr>
          <tr><td>Screen Map (Figma)</td><td>Visual cards + connections</td></tr>
        </tbody>
      </table>

      <h4>Key Features</h4>
      <ul>
        <li>สร้าง flow diagrams อัตโนมัติด้วย Mermaid.js → FigJam</li>
        <li>Navigation patterns ตาม platform (iOS Tab Bar, Android Bottom Nav, Web Sidebar)</li>
        <li>ตรวจ flow ด้วย Hick's Law, Miller's Law, H1/H3/H5</li>
        <li>สร้าง visual screen map ใน Figma ด้วย create_connections</li>
      </ul>

      <h4>Trigger Words</h4>
      <p><code>user flow</code>, <code>flow</code>, <code>IA</code>, <code>information architecture</code>, <code>journey</code>, <code>sitemap</code>, <code>screen map</code>, <code>navigation</code>, <code>task flow</code></p>
    </div>
  </details>

  <!-- ─── figma-accessibility-audit.md ─── -->
  <details>
    <summary><span style="color:var(--orange);">♿</span> figma-accessibility-audit.md — Accessibility Audit Skill <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-accessibility-audit.md</div>
      <div class="info-box note">
        <span class="icon">📋</span>
        <div>Copy เนื้อหาด้านล่างทั้งหมด แล้ว save เป็นไฟล์ <code>~/.claude/commands/figma-accessibility-audit.md</code></div>
      </div>

      <h4>Overview</h4>
      <p>ตรวจสอบ Accessibility อย่างครบถ้วนตาม WCAG 2.1 — ครอบคลุม 7 หมวด ไม่ใช่แค่สี</p>
      <p><strong>Flow:</strong> Capture → Read Guidelines → Audit (7 Categories) → Score → Report → Fix</p>

      <h4>7 Audit Categories</h4>
      <table>
        <thead><tr><th>หมวด</th><th>Weight</th><th>WCAG Criteria</th></tr></thead>
        <tbody>
          <tr><td>Color Contrast</td><td>25%</td><td>1.4.3 / 1.4.6</td></tr>
          <tr><td>Touch Targets</td><td>15%</td><td>2.5.5 / 2.5.8</td></tr>
          <tr><td>Screen Reader</td><td>20%</td><td>1.1.1 / 4.1.2</td></tr>
          <tr><td>Color Independence</td><td>10%</td><td>1.4.1</td></tr>
          <tr><td>Keyboard Navigation</td><td>10%</td><td>2.1.1 / 2.4.7</td></tr>
          <tr><td>Text &amp; Readability</td><td>10%</td><td>1.4.4 / 1.4.12</td></tr>
          <tr><td>Motion &amp; Cognitive</td><td>10%</td><td>2.3.1 / 2.3.3</td></tr>
        </tbody>
      </table>

      <h4>Key Features</h4>
      <ul>
        <li>ตรวจ contrast ทุกคู่สีด้วยสูตร relative luminance</li>
        <li>ตรวจ touch targets (44pt iOS / 48dp Android / 44px Web)</li>
        <li>Screen reader checks: labels, alt text, heading structure, reading order</li>
        <li>Color blindness simulation (Protanopia, Deuteranopia, Tritanopia)</li>
        <li>Keyboard navigation: focus order, focus visible, skip links, traps</li>
        <li>Text readability: line height, line length, min font size, Dynamic Type</li>
        <li>Motion: reduce motion support, auto-play, flashing content</li>
        <li>WCAG Violations Summary พร้อม criterion reference</li>
        <li>Priority action items (P0-P3)</li>
      </ul>

      <h4>Trigger Words</h4>
      <p><code>accessibility</code>, <code>a11y</code>, <code>WCAG</code>, <code>accessible</code>, <code>ตรวจการเข้าถึง</code>, <code>ตรวจ contrast</code>, <code>touch target</code></p>
    </div>
  </details>

  <!-- ─── figma-design-system.md ─── -->
  <details>
    <summary><span style="color:var(--accent);">🎨</span> figma-design-system.md — Design System Creation Skill <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-design-system.md</div>
      <div class="info-box note">
        <span class="icon">📋</span>
        <div>Copy เนื้อหาด้านล่างทั้งหมด แล้ว save เป็นไฟล์ <code>~/.claude/commands/figma-design-system.md</code></div>
      </div>

      <h4>Overview</h4>
      <p>สร้าง Design System ทั้งระบบ — tokens, typography, color system, components จนถึง documentation</p>
      <p><strong>Flow:</strong> Requirements → Read References → Define Foundations → Design Components → Preview → Build in Figma → Document</p>

      <h4>Foundations</h4>
      <table>
        <thead><tr><th>Foundation</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td>Color System</td><td>Scale (50-950) + Semantic + Light/Dark + WCAG verified</td></tr>
          <tr><td>Typography Scale</td><td>15 levels (display → label) + font family</td></tr>
          <tr><td>Spacing</td><td>4px base (space-0 → space-20)</td></tr>
          <tr><td>Shape</td><td>Radius tokens (none → full)</td></tr>
          <tr><td>Elevation</td><td>Shadow tokens (0-4 levels)</td></tr>
        </tbody>
      </table>

      <h4>Component Hierarchy (Atomic Design)</h4>
      <ul>
        <li><strong>Atoms</strong>: Button, Text Field, Checkbox, Radio, Toggle, Badge, Chip, Avatar, Divider</li>
        <li><strong>Molecules</strong>: Search Bar, List Item, Form Field, Menu Item, Snackbar, Tab</li>
        <li><strong>Organisms</strong>: App Bar, Navigation, Card, Dialog, Bottom Sheet, Data Table, Form</li>
      </ul>

      <h4>Per-Component Spec</h4>
      <p>ทุก component กำหนด: Anatomy, Variants (filled/outlined/text), Sizes (S/M/L), States (default/hover/pressed/focused/disabled/loading), Accessibility, Spacing Rules</p>

      <h4>Trigger Words</h4>
      <p><code>design system</code>, <code>component library</code>, <code>UI kit</code>, <code>style guide</code>, <code>tokens</code>, <code>pattern library</code></p>
    </div>
  </details>

  <!-- ─── figma-responsive-design.md ─── -->
  <details>
    <summary><span style="color:var(--blue);">📱</span> figma-responsive-design.md — Responsive Design Skill <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-responsive-design.md</div>
      <div class="info-box note">
        <span class="icon">📋</span>
        <div>Copy เนื้อหาด้านล่างทั้งหมด แล้ว save เป็นไฟล์ <code>~/.claude/commands/figma-responsive-design.md</code></div>
      </div>

      <h4>Overview</h4>
      <p>ออกแบบ UI ที่ทำงานได้ดีบนทุกขนาดหน้าจอ — จาก Mobile เล็กสุดไปจน Desktop จอใหญ่</p>
      <p><strong>Flow:</strong> Requirements → Read References → Define Breakpoints → Design Adaptation Rules → Preview → Build in Figma</p>

      <h4>Standard Breakpoints</h4>
      <table>
        <thead><tr><th>Breakpoint</th><th>Width</th><th>Device</th><th>Columns</th></tr></thead>
        <tbody>
          <tr><td>xs</td><td>&lt; 360px</td><td>Small phone</td><td>4</td></tr>
          <tr><td>sm</td><td>360-599px</td><td>Phone</td><td>4</td></tr>
          <tr><td>md</td><td>600-904px</td><td>Tablet portrait</td><td>8</td></tr>
          <tr><td>lg</td><td>905-1239px</td><td>Tablet/Desktop</td><td>12</td></tr>
          <tr><td>xl</td><td>1240-1439px</td><td>Desktop</td><td>12</td></tr>
          <tr><td>2xl</td><td>&ge; 1440px</td><td>Large desktop</td><td>12</td></tr>
        </tbody>
      </table>

      <h4>Adaptation Strategies</h4>
      <ul>
        <li><strong>Reflow</strong>: Cards vertical → horizontal</li>
        <li><strong>Reveal</strong>: Show hidden sidebar</li>
        <li><strong>Hide</strong>: Remove non-essential on mobile</li>
        <li><strong>Resize</strong>: Full-width → fixed width</li>
        <li><strong>Transform</strong>: Bottom sheet → side panel</li>
      </ul>

      <h4>Navigation Adaptation</h4>
      <ul>
        <li><strong>Mobile</strong>: Bottom Tab Bar (3-5 items)</li>
        <li><strong>Tablet</strong>: Navigation Rail (side icons)</li>
        <li><strong>Desktop</strong>: Sidebar Navigation (full)</li>
      </ul>

      <h4>Key Features</h4>
      <ul>
        <li>Content adaptation rules per section (hero, card grid, table, form)</li>
        <li>Typography &amp; spacing adaptation per breakpoint</li>
        <li>Responsive React preview ที่ resize ได้จริง</li>
        <li>สร้าง multiple Figma frames (Mobile + Tablet + Desktop)</li>
        <li>Annotations อธิบาย adaptation rules + connection lines ระหว่าง sizes</li>
      </ul>

      <h4>Trigger Words</h4>
      <p><code>responsive</code>, <code>adaptive</code>, <code>breakpoint</code>, <code>หลายขนาด</code>, <code>mobile tablet desktop</code>, <code>responsive design</code></p>
    </div>
  </details>

  <!-- ─── figma-ux-writer.md ─── -->
  <details>
    <summary><span style="color:var(--accent);">✍️</span> figma-ux-writer.md — UX Writer Skill (TH + EN) <span style="background:#1bc47d;color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;margin-left:8px;">NEW</span></summary>
    <div class="details-body">
      <div class="file-badge"><span class="dot skill"></span> ~/.claude/commands/figma-ux-writer.md</div>
      <div class="info-box note">
        <span class="icon">📋</span>
        <div>Copy เนื้อหาด้านล่างทั้งหมด แล้ว save เป็นไฟล์ <code>~/.claude/commands/figma-ux-writer.md</code></div>
      </div>

      <h4>Overview</h4>
      <p>เขียน UX Copy ที่ผู้ใช้อ่านแล้วเข้าใจทันที ไม่มีข้อสงสัย — ทั้งภาษาไทย (หลัก) และอังกฤษ ในระดับมืออาชีพ</p>
      <p><strong>Flow:</strong> Context → Voice &amp; Tone → Write → Review &amp; Polish + Spell Check + Correction Log → Apply (Figma)</p>

      <h4>Voice Attributes (Standard)</h4>
      <table>
        <thead><tr><th>Attribute</th><th>คำอธิบาย</th></tr></thead>
        <tbody>
          <tr><td><strong>ชัดเจน</strong></td><td>ตรงประเด็น อ่านรู้เรื่องในครั้งเดียว</td></tr>
          <tr><td><strong>เป็นมิตร</strong></td><td>เข้าถึงง่าย ไม่เป็นทางการเกินไป</td></tr>
          <tr><td><strong>ช่วยเหลือ</strong></td><td>บอกสิ่งที่ต้องทำ ไม่ใช่แค่บอกปัญหา</td></tr>
          <tr><td><strong>เคารพ</strong></td><td>ไม่โทษผู้ใช้ ไม่ใช้ศัพท์เทคนิค</td></tr>
          <tr><td><strong>มั่นใจ</strong></td><td>สื่อสารอย่างแน่นอน ไม่คลุมเครือ</td></tr>
        </tbody>
      </table>

      <h4>Tone ตามสถานการณ์</h4>
      <table>
        <thead><tr><th>สถานการณ์</th><th>Tone</th><th>ไทย</th><th>English</th></tr></thead>
        <tbody>
          <tr><td>สำเร็จ</td><td>อบอุ่น</td><td>สมัครสมาชิกเรียบร้อยแล้ว</td><td>You're all set!</td></tr>
          <tr><td>ข้อผิดพลาด</td><td>สงบ, ช่วยเหลือ</td><td>กรอกอีเมลไม่ถูกรูปแบบ ลองตรวจอีกครั้ง</td><td>That doesn't look right. Please check and try again.</td></tr>
          <tr><td>คำเตือน</td><td>จริงจัง</td><td>ลบแล้วจะกู้คืนไม่ได้</td><td>This can't be undone.</td></tr>
          <tr><td>ว่างเปล่า</td><td>แนะนำ</td><td>ยังไม่มีรายการ เริ่มเพิ่มตัวแรกเลย</td><td>Nothing here yet. Add your first item.</td></tr>
          <tr><td>Onboarding</td><td>ตื่นเต้น</td><td>มาเริ่มกันเลย!</td><td>Let's get you started!</td></tr>
        </tbody>
      </table>

      <h4>Copy Types</h4>
      <ul>
        <li><strong>Buttons/CTAs</strong>: เริ่มด้วยกริยา, เจาะจง, 2-4 คำ</li>
        <li><strong>Error Messages</strong>: สูตร [สิ่งที่เกิดขึ้น] + [วิธีแก้]</li>
        <li><strong>Empty States</strong>: สูตร [สิ่งที่จะอยู่ตรงนี้] + [ทำอย่างไรให้มี]</li>
        <li><strong>Form Labels</strong>: ชัดเจน, placeholder เป็นตัวอย่างจริง</li>
        <li><strong>Confirmations</strong>: บอกผลที่จะเกิด + ย้อนกลับได้ไหม</li>
        <li><strong>Loading</strong>: บอกว่ากำลังทำอะไร ไม่ใช่แค่ "กำลังโหลด..."</li>
      </ul>

      <h4>ภาษาไทย — หลักเฉพาะ</h4>
      <ul>
        <li>ไม่ใช้ "กรุณา" / "ของคุณ" ทุกที่</li>
        <li>สะกดทับศัพท์ตามราชบัณฑิต: "อีเมล" (ไม่ใช่ อีเมล์), "เว็บไซต์"</li>
        <li>ทับศัพท์ได้ถ้าคนเข้าใจง่ายกว่า</li>
      </ul>

      <h4>ภาษาอังกฤษ — หลักเฉพาะ</h4>
      <ul>
        <li>Sentence case / Use contractions / Active voice</li>
        <li>Front-load keywords / No jargon</li>
      </ul>

      <h4>10-Point Review Checklist</h4>
      <ol>
        <li>ชัดเจน — อ่านครั้งเดียวเข้าใจ?</li>
        <li>กระชับ — ตัดคำไหนออกได้?</li>
        <li>มีประโยชน์ — บอกสิ่งที่ต้องทำต่อ?</li>
        <li>เหมาะกับ Tone — ตรงกับสถานการณ์?</li>
        <li>ไม่โทษผู้ใช้ — ภาษาเชิงบวก/กลาง?</li>
        <li>เข้าถึงได้ — ไม่มีศัพท์เทคนิค?</li>
        <li>สม่ำเสมอ — ใช้คำเดียวกันทั้ง app?</li>
        <li>ครบทุก state — success, error, empty, loading?</li>
        <li>ไม่ยาวเกินกรอบ — พอดี layout?</li>
        <li>สะกดถูก — ตรวจ typo? (ดู Spell &amp; Grammar Check ด้านล่าง)</li>
      </ol>

      <h4>Spell &amp; Grammar Check (TH + EN)</h4>
      <ul>
        <li><strong>คำไทยที่มักผิด</strong>: ทับศัพท์ (อัพเดท→อัปเดต, อีเมล์→อีเมล, เว็ปไซต์→เว็บไซต์, แอปพลิเคชั่น→แอปพลิเคชัน), คำทั่วไป (กรุณณา→กรุณา, สังเกตุ→สังเกต)</li>
        <li><strong>คำอังกฤษที่มักผิด</strong>: Spelling (Recieve→Receive, Succesful→Successful, Occured→Occurred), Grammar (Login vs Log in, Its vs It's)</li>
        <li><strong>ไวยากรณ์</strong>: ไทย — ตัด "ทำการ" ซ้ำซ้อน, "สามารถ...ได้" ที่ไม่จำเป็น, "ของ" ซ้ำซ้อน / EN — subject-verb agreement, compound verbs (set up vs setup)</li>
        <li><strong>Correction Log</strong>: ตาราง — ตำแหน่ง | ข้อความเดิม | ข้อความที่แก้ | ประเภทข้อผิด | เหตุผล + Summary สรุปจำนวนข้อผิดแต่ละประเภท</li>
      </ul>

      <h4>Output</h4>
      <ul>
        <li><strong>Copy Deck Table</strong>: ทุก element + ไทย/EN + tone + max length</li>
        <li><strong>Terminology Table</strong>: ทุก concept ใช้คำเดียวกันทั้ง app</li>
        <li><strong>Content Audit</strong>: review copy ที่มี + recommendation</li>
        <li><strong>Correction Log</strong>: รายการคำผิดที่แก้ + เหตุผล + Summary</li>
        <li>Optional: ใส่ text เข้า Figma ผ่าน MCP</li>
      </ul>

      <h4>Trigger Words</h4>
      <p><code>UX writing</code>, <code>copy</code>, <code>เขียน copy</code>, <code>ข้อความ</code>, <code>microcopy</code>, <code>tone of voice</code>, <code>content design</code>, <code>ตรวจคำผิด</code>, <code>spell check</code>, <code>เช็คคำผิด</code>, <code>proofread</code>, <code>grammar check</code></p>
    </div>
  </details>

</section>

<!-- ════════════════════ GLOSSARY ════════════════════ -->
<section class="section" id="glossary">
  <h2><span class="num" style="font-size:14px;">A</span> คำศัพท์สำคัญ</h2>
  <p class="section-subtitle">Glossary</p>

  <dl class="glossary-grid">
    <div class="glossary-item">
      <dt>MCP</dt>
      <dd>Model Context Protocol — มาตรฐานการเชื่อมต่อ AI กับ tools ภายนอก</dd>
    </div>
    <div class="glossary-item">
      <dt>WebSocket</dt>
      <dd>เทคโนโลยีสื่อสารแบบ real-time ระหว่างโปรแกรม</dd>
    </div>
    <div class="glossary-item">
      <dt>Channel ID</dt>
      <dd>รหัสห้องที่ Claude กับ Figma Plugin ใช้คุยกัน</dd>
    </div>
    <div class="glossary-item">
      <dt>Node</dt>
      <dd>Element ใดๆ ใน Figma (frame, text, rectangle ฯลฯ)</dd>
    </div>
    <div class="glossary-item">
      <dt>Node ID</dt>
      <dd>รหัสเฉพาะของแต่ละ element (เช่น "1:23")</dd>
    </div>
    <div class="glossary-item">
      <dt>Auto Layout</dt>
      <dd>ระบบจัด layout อัตโนมัติใน Figma</dd>
    </div>
    <div class="glossary-item">
      <dt>CLI</dt>
      <dd>Command Line Interface — โปรแกรมที่ใช้ผ่าน Terminal</dd>
    </div>
    <div class="glossary-item">
      <dt>Terminal</dt>
      <dd>หน้าต่างสำหรับพิมพ์คำสั่ง (เหมือน Command Prompt บน Windows)</dd>
    </div>
    <div class="glossary-item">
      <dt>Extension</dt>
      <dd>ส่วนเสริมที่ติดตั้งเพิ่มใน VS Code</dd>
    </div>
    <div class="glossary-item">
      <dt>Plugin</dt>
      <dd>ส่วนเสริมที่ติดตั้งเพิ่มใน Figma</dd>
    </div>
    <div class="glossary-item">
      <dt>stdio</dt>
      <dd>Standard Input/Output — วิธีส่งข้อมูลระหว่างโปรแกรม</dd>
    </div>
  </dl>
</section>

</div><!-- /.container -->

<!-- ════════════════════ FOOTER ════════════════════ -->
<footer class="footer">
  <p>จัดทำสำหรับ <strong>Knowledge Sharing</strong> ภายในทีม</p>
  <p>หากมีคำถามหรือพบปัญหา สามารถถามในช่องทีมได้เลย</p>
  <p style="margin-top:12px; opacity:0.6;">v1.0 — February 2025</p>
</footer>

</body>
</html>
